-- Generated by scripts/generate-sync-sql.mjs — do not edit by hand.
-- Run once in the Supabase SQL Editor. Safe to re-run: every statement is idempotent.

begin;

-- 1. Stable option ids: the correct answer stops being an array position.
alter table academy_quiz_questions
  add column if not exists option_ids text[],
  add column if not exists correct_option_id text;

comment on column academy_quiz_questions.option_ids is 'Stable id per option, derived from its text (src/lib/optionIds.js). Reordering options no longer moves the correct answer.';
comment on column academy_quiz_questions.correct_option_id is 'Value of option_ids that is correct. correct_option_index is kept for older clients.';

-- 2. Backfill stable ids on the 259 questions already stored.
update academy_quiz_questions q
set option_ids = v.option_ids, correct_option_id = v.correct_option_id
from (values
  ('82a668b2-86da-4a1f-a700-25e795b63437'::uuid, ARRAY['1m4nhpj', 'fqadux', '2k42cz', 'xuuhl0']::text[], '2k42cz'),
  ('745c23c6-a05e-4428-8408-581a49d1e1e0'::uuid, ARRAY['w2uclm', '1xgc78l', 'z2b6ti', '1fl20wd']::text[], '1fl20wd'),
  ('0d912358-8c38-429b-ba98-1ccee7bb8a35'::uuid, ARRAY['5i60zl', '1mh3ua5', 'rljrh7', '17dsto8']::text[], 'rljrh7'),
  ('bb66b7bc-dc9e-4b1a-985d-1efc792bba9c'::uuid, ARRAY['gty7tc', '15lklch', 'bjcnej', 'vqa62i']::text[], '15lklch'),
  ('96401a95-a891-4bb0-8c69-36a4e2b5002a'::uuid, ARRAY['1t93jwh', 'f632ey', '1ib4fin', 'u3qj7a']::text[], 'u3qj7a'),
  ('0161c59c-99cb-4531-b6d7-a0422c43ea2a'::uuid, ARRAY['1u6c9ix', '1rb0tjr', '47ee5n', 'uy42m8']::text[], 'uy42m8'),
  ('a0eca50c-0fb3-4cb1-9d62-8259c5174480'::uuid, ARRAY['g2oxse', '10ijbad', '19ghzbg', '33kk2l']::text[], '33kk2l'),
  ('83245c0c-aa04-44fa-b677-880d42818e56'::uuid, ARRAY['y99zi7', '1m3u8u', 'mj0m4p', 'rrk2ai']::text[], 'y99zi7'),
  ('6fca4021-bb3c-4f15-ac83-1c7196f96dac'::uuid, ARRAY['6ttlvu', '13d8nq2', '1spasp6', '9ibfnr']::text[], '6ttlvu'),
  ('0849b6e0-ad52-4a55-af25-9430f39a716e'::uuid, ARRAY['16owoch', 'vgwcy7', '1vlmclg', '583za5']::text[], '1vlmclg'),
  ('d4554e50-7ee7-4eda-b070-157385a93725'::uuid, ARRAY['j9e31h', '124vg2q', '1pfp6fx', '1iahtcr']::text[], '1pfp6fx'),
  ('5ab59f5b-062a-4199-86d5-4cec1d77323b'::uuid, ARRAY['y588g8', '1omkvy1', 'ib1n2i', '1q19ada']::text[], 'y588g8'),
  ('2cf64d46-4fcc-4abc-b32c-b710ec8f9f01'::uuid, ARRAY['eubi7f', '3l1oah', '1kub8ic', '29udxe']::text[], 'eubi7f'),
  ('a8ac7090-895a-4235-ba56-a92e0dd0856f'::uuid, ARRAY['o582tx', '1h22r54', '1sqtpbj', '42airr']::text[], 'o582tx'),
  ('727e37ff-9015-4d95-8c86-a71163c71de6'::uuid, ARRAY['mvdhz5', '11cyh29', '1alnwzh', '1rlhz8x']::text[], 'mvdhz5'),
  ('c2ce8cae-4724-4645-b807-0e2ebafa25b4'::uuid, ARRAY['1ai0065', 'eoydac', '1q807s', 'cpa5bk']::text[], 'cpa5bk'),
  ('6e62a3ea-870b-4715-bdca-1fef96fa7921'::uuid, ARRAY['8bc8yj', 'ogxxds', 'tel1ka', '1e7h3np']::text[], '1e7h3np'),
  ('70ebc2e9-1b64-4104-9b5d-7bcd72de4292'::uuid, ARRAY['5wnh5q', '1s0bgfg', '1fl8k3r', 'titbvp']::text[], 'titbvp'),
  ('330e779d-02d6-4aec-b16d-3f6c0f8a4d8e'::uuid, ARRAY['1fpebcz', '1tu68uy', '1otetum', '9icvoo']::text[], '1otetum'),
  ('0271dd57-ec07-41d8-86c8-8b7c76f599d9'::uuid, ARRAY['1076wa0', '1r29nt1', '99x91m', '1xly6e6']::text[], '1r29nt1'),
  ('e61bee45-c214-47b3-8e4a-e5d682a99ac3'::uuid, ARRAY['1rmbf17', '1svfm6r', '189q7p2', 'l21ldd']::text[], '189q7p2'),
  ('308a012f-842b-4659-bdbb-bd4816649d87'::uuid, ARRAY['1e3v7el', 'm5pula', 'gi4bb7', '1qt553k']::text[], 'gi4bb7'),
  ('2d7fc198-cee4-4409-911b-0c7b7fba6158'::uuid, ARRAY['18ekijt', '1xy5y0q', '13dxbhs', '1501jw9']::text[], '13dxbhs'),
  ('dcf14e7c-07c5-40ac-9752-35cbf22bd647'::uuid, ARRAY['1tucqp1', 'y30rdq', '1anmz7t', 'pmmaay']::text[], '1tucqp1'),
  ('4365735b-0069-4994-bbc6-498a8a092b28'::uuid, ARRAY['1ilha6j', '1py92xh', '7pj1e', '3xs19z']::text[], '1ilha6j'),
  ('e32e39ac-476d-4771-b57d-0f1d13d7b5f8'::uuid, ARRAY['1nxtnyy', 'thxefw', '1del9oq', '1fvcprq']::text[], '1nxtnyy'),
  ('31794e03-ac77-4853-881c-780113d6722a'::uuid, ARRAY['1bohd1x', 'mjqv95', '14q389k', 'bvula2']::text[], 'mjqv95'),
  ('3dae3222-3aa7-4bed-a1e3-f235097e2638'::uuid, ARRAY['4u2cyr', '103q5ov', 'eb2beh', 'pw43jb']::text[], '4u2cyr'),
  ('b71f8c3d-5088-4b86-a3aa-9cd428089b75'::uuid, ARRAY['azomn1', 'jxhkkk', '1oukf4v', '13rd7al']::text[], 'azomn1'),
  ('2ca0fb26-63ce-4401-8122-fba8dee95d2b'::uuid, ARRAY['3sjyay', 'i70ysr', '1v3mil7', 'o21q9k']::text[], '3sjyay'),
  ('8448ac9d-23b8-4e24-8942-06804387bcc8'::uuid, ARRAY['xr8fto', '1f20dsv', 'ue4s6x', '114c3gf']::text[], 'xr8fto'),
  ('7449fbcb-3e3c-4906-961a-3621f18c2b59'::uuid, ARRAY['1alldp2', 'dfk1f3', 'cvpd7h', '1v094el']::text[], 'dfk1f3'),
  ('c11db088-c3f3-450b-8814-92838ad9a15d'::uuid, ARRAY['suwx6x', '15qkge7', '1yv6x7d', '1dp5k9r']::text[], '15qkge7'),
  ('3fed8074-7472-4644-aa18-3fc0f8b36d0b'::uuid, ARRAY['x6yrv1', '133squk', '10v70cx', '1m3g9mz']::text[], '133squk'),
  ('9bf0a0bd-b73d-4380-8254-4297ed418fc2'::uuid, ARRAY['194gqat', '1d470lb', 'nygirt', 'edjw4u']::text[], '1d470lb'),
  ('01239f2c-c45b-4299-99ba-d4d14b9edfff'::uuid, ARRAY['wyhku7', '1zb8mv', '1lgf3cx', '1e1i55l']::text[], '1zb8mv'),
  ('8ff2232d-ae8b-4e02-bb22-283b2f84d988'::uuid, ARRAY['2495zd', '1pb3tiz', '1al70vx', 'ymiqt6']::text[], 'ymiqt6'),
  ('58da767c-5067-444c-b429-46029e00ee0f'::uuid, ARRAY['1odzhl1', '1odzhkz', '1odzhl3', '1ndzem2']::text[], '1odzhl1'),
  ('68f47ca0-9350-47fb-89b8-9c959a048efe'::uuid, ARRAY['14q389k', '49zupx', '15ilq5k', '18ypf1q']::text[], '15ilq5k'),
  ('2c4b9360-0c60-498a-a3a2-bc1d54ec44b1'::uuid, ARRAY['pviv6b', '1fys1u6', '11rlej6', '1b6389o']::text[], 'pviv6b'),
  ('a478e1a1-2df8-4e6b-b66a-c0df192c7da9'::uuid, ARRAY['15uor2h', '12dsacl', '1mxrlu', '1md9ltd']::text[], '12dsacl'),
  ('ae961917-cf7c-43b4-a9ec-554ac5d9ec6f'::uuid, ARRAY['3rz045', '8ig6a8', 'fl9941', '1fhiiyi']::text[], '8ig6a8'),
  ('662e33e0-a410-45ea-b77d-1882ae0830f9'::uuid, ARRAY['7tpy16', 'z91hnh', '1iisz0n', 'krac4k']::text[], 'z91hnh'),
  ('df09626c-6c8b-4ff9-9292-0a4273bb8938'::uuid, ARRAY['kw5kmg', '1xhtmg4', '1t9k8bo', 'fibz5c']::text[], 'kw5kmg'),
  ('acc13fb4-5e66-4ca2-981d-4c610ce2a1ed'::uuid, ARRAY['808z6z', '1n95z4f', 'i053v0', 'aw9yb0']::text[], '1n95z4f'),
  ('0ac1a0b2-967a-4f97-9b78-c2ea238d1d96'::uuid, ARRAY['99o2i5', '1efxj3b', 'j8cihd', '1cfu16g']::text[], '99o2i5'),
  ('b902d4b2-2b0c-45b8-9974-93636f7ba9c9'::uuid, ARRAY['kyxs82', 'i70ysr', '3sjyay', '45s9ug']::text[], 'kyxs82'),
  ('4fdb6920-28a3-4481-93d0-d62e7983813d'::uuid, ARRAY['8krjb7', 'rt8bnq', 'm7fuui', '1q8l2n6']::text[], 'rt8bnq'),
  ('fd971819-07f1-464b-b0d3-526a2fe911a5'::uuid, ARRAY['10pvshh', 'oj322j', 'z644mt', 'qtq0m']::text[], 'z644mt'),
  ('a0a7ff87-0a44-411e-8c2c-5cd70d63407f'::uuid, ARRAY['1g0hnwg', '71rsny', '1c2s268', '99e3oz']::text[], '1g0hnwg'),
  ('1108cf41-6b2b-4d91-8bbf-b4ee66dc2336'::uuid, ARRAY['a00sw9', '1hcv67g', 'y1nip5', 'k73ssl']::text[], 'k73ssl'),
  ('7ae851ac-9bf8-4aa1-99bc-88a12da86a68'::uuid, ARRAY['375xws', '375zla', '37619s', '375x2j']::text[], '37619s'),
  ('a7a6e193-099e-4da7-bc8e-e38cffe58cf9'::uuid, ARRAY['45gvyx', 'rol1ko', 'ovs516', '1maxkvj']::text[], 'ovs516'),
  ('6501783e-5502-4d8e-9231-a283c9dc68db'::uuid, ARRAY['az8vzg', '6p71ga', 'haum7c', '1tftor2']::text[], '1tftor2'),
  ('2ca2e5d5-ec78-4016-bd2d-f4817a1982f7'::uuid, ARRAY['8vitnh', '37gwsl', 'iyrt1q', '162qqrw']::text[], '37gwsl'),
  ('5148026d-c700-4c61-9fb9-a54ca470899a'::uuid, ARRAY['1i8mlvp', '1oepw75', '1butvq2', '3crb5f']::text[], '1oepw75'),
  ('fe4fd31f-de78-4390-9029-778b41f897da'::uuid, ARRAY['sbk3uc', '1k0nk5i', '1aujs8y', 'uywd07']::text[], '1aujs8y'),
  ('f002e162-3e8a-44ef-80a2-07222aa48b2d'::uuid, ARRAY['11u3vx5', 'q4ya18', '9vley8', 'pysokv']::text[], '11u3vx5'),
  ('26e26797-c667-463c-9411-df47754138f8'::uuid, ARRAY['tqwnje', '1fz1pvd', '1sl5scz', '1fvcprq']::text[], '1fvcprq'),
  ('14795221-72b6-42bc-9436-611bc95a1ffd'::uuid, ARRAY['1e3d2o3', 'yv1og6', '1m08be0', 't9rkbc']::text[], 'yv1og6'),
  ('fcc22ac5-171c-4075-987f-0ab1854386f3'::uuid, ARRAY['as3w47', 'pf38dl', '9nqo8m', 'e57jqy']::text[], 'as3w47'),
  ('166e31f0-b964-4c67-9c95-c0308e155bc9'::uuid, ARRAY['1r6tuzk', 'pafddn', 'cfutxx', '1e43i51']::text[], '1e43i51'),
  ('4d2291e1-bcad-4e55-9e6b-ee1ecf7ccddd'::uuid, ARRAY['1fnnidb', '227lrw', '1f5k79v', '8vitnh']::text[], '1f5k79v'),
  ('d4db380a-5774-46f0-88ec-65ba4633cda0'::uuid, ARRAY['hgbkie', 'hlra5l', '1kr3p29', 'ttsqz3']::text[], '1kr3p29'),
  ('923e88e9-ff42-47a3-a2f4-0f720420b385'::uuid, ARRAY['xwbueb', 'dj61m6', '6m47a4', '1fvcprq']::text[], '1fvcprq'),
  ('f9d279df-53a6-4f53-9a10-5d64840e07e1'::uuid, ARRAY['hbjdnv', '227lrw', '8vitnh', '1f5k79v']::text[], '227lrw'),
  ('f0451ee4-1da9-472d-80db-bf0bd47ca581'::uuid, ARRAY['b49g5y', '1r6tuzk', '1chv7zh', 'pafddn']::text[], '1r6tuzk'),
  ('f3accb94-48e6-4603-ab67-ef4144415bdc'::uuid, ARRAY['rpc555', '1ctsrqf', '1qkklfd', '1a0312f']::text[], 'rpc555'),
  ('a2dd0517-17e1-4f5e-bba5-f931e217006f'::uuid, ARRAY['1ecpxsk', '1trpj88', 'i3qx34', '7l06cz']::text[], '7l06cz'),
  ('4246c79e-ae71-4d26-8c0d-8a6d5f9f9de9'::uuid, ARRAY['4wlco9', 'zuujab', 'z6cnay', 's50wa0']::text[], '4wlco9'),
  ('875a6b6f-8b37-446b-8f6a-1f3e1966abe9'::uuid, ARRAY['190gpe5', '2hw7qh', 'qb72yx', 'ihgbn2']::text[], '2hw7qh'),
  ('bca0a6c8-d17c-4eb8-bd32-12ba8ac7e6d8'::uuid, ARRAY['1f5k79v', '59y4ti', 'hbjdnv', 'iyrt1q']::text[], 'hbjdnv'),
  ('56e42b9f-eca5-4b5a-827d-6b5eb6aa3be9'::uuid, ARRAY['aiwprq', '1wo6s3s', 'xgoc5w', '1fvcprq']::text[], '1wo6s3s'),
  ('b5881254-058e-4b2b-a924-5c270ead264b'::uuid, ARRAY['pvh3cv', 'lj3giw', 'acr2wq', 'ujtdjt']::text[], 'acr2wq'),
  ('12659815-37e7-4d76-bd8f-b721d832f6b5'::uuid, ARRAY['mxqfua', '13v1vht', 'rly96v', '1rqqj8k']::text[], 'mxqfua'),
  ('9c250818-0799-49f1-b1fc-ab126a1e4479'::uuid, ARRAY['1iale8d', 'rz7ued', '3w9ajp', '551i9v']::text[], 'rz7ued'),
  ('9a3a9347-7489-408f-9cdc-0a3e54f5b70d'::uuid, ARRAY['3lmhqr', '5yq6ar', '1nsiutx', 'e1wsbn']::text[], 'e1wsbn'),
  ('cda1bae7-ab27-4dee-8c24-99833ca4e3b7'::uuid, ARRAY['qcui40', '1d04599', '9l9e73', 'uyi2fc']::text[], 'qcui40'),
  ('e6919b05-12d5-4da0-810e-7a9581e192b3'::uuid, ARRAY['cy6jjp', 'n45iqr', 'otmstq', '1fvcprq']::text[], 'otmstq'),
  ('c5ea2f60-9016-45b3-a069-0a6ad190dc73'::uuid, ARRAY['czz4vg', '18n6vxn', 'gozl1p', 'lyaz8h']::text[], '18n6vxn'),
  ('cd73e5d2-6f5f-43d0-a432-913e50a9c516'::uuid, ARRAY['1jv2qxp', 'k7pvsm', '1v6bzby', 'vn9jvy']::text[], '1jv2qxp'),
  ('3e664c94-883f-4a58-99ec-6c41b4983e3f'::uuid, ARRAY['zwu8s3', '1aofmfq', 'lat54l', '6zyb1g']::text[], '1aofmfq'),
  ('d7c007d3-e0df-475a-86e5-270a9a0f90b4'::uuid, ARRAY['1m90ota', '5bxv4s', '184iuy7', 'rnsdha']::text[], '1m90ota'),
  ('7759ac01-a161-43df-bc11-6cd9945b07bc'::uuid, ARRAY['8uk921', 'wd7ju0', '156bb7y', 'nkn3dg']::text[], 'wd7ju0'),
  ('737d2847-a45c-49ed-a1ce-6c304da59aaf'::uuid, ARRAY['15pw8iz', 'o87vbf', 'a7h8h4', '1ep7ma8']::text[], '1ep7ma8'),
  ('2be9fcc8-a803-4c0c-89bb-c851ff0a1e87'::uuid, ARRAY['rgtjpf', '1ezttw2', '6ehjr3', 'pbfmn2']::text[], '1ezttw2'),
  ('66154eaf-1ce5-48b4-b9c9-ba57657c9d70'::uuid, ARRAY['1mu0ie0', '12s33j1', 'ausogn', '1csccoc']::text[], '1mu0ie0'),
  ('73b8f99e-0847-4136-afb4-db31b299fbd8'::uuid, ARRAY['174fg3l', 'g5nhyd', '1pij58f', 'f0e207']::text[], '1pij58f'),
  ('8ce9b45f-59ca-45cd-b4f8-320bca6425d9'::uuid, ARRAY['s5mipm', 'obpuiy', 'qfv1jm', '3qbbhx']::text[], 'qfv1jm'),
  ('077a604f-d0e5-4fc3-8e3c-8afc9d030c6d'::uuid, ARRAY['ep3nz', 'ucmp5i', '1ttsbqn', 'up06zy']::text[], 'up06zy'),
  ('a0232a71-8fb1-47ff-b36d-e2688865d2db'::uuid, ARRAY['1p6ubl0', '81vl3p', 'hpofaf', 'ayb1yf']::text[], '1p6ubl0'),
  ('a5dc70b4-540e-496b-96a3-9e8efd686b26'::uuid, ARRAY['1my70s2', '1spbeab', 'yhauhl', '81vl3p']::text[], 'yhauhl'),
  ('20842f62-e35c-4856-8289-1ce98813c113'::uuid, ARRAY['ub52ev', 'y82f1q', '1vl711i', '1ezttw2']::text[], 'y82f1q'),
  ('478b93ed-2c5c-471f-adf3-596c5f21edef'::uuid, ARRAY['n3ei4a', '1h0eoqw', '1ij2zcb', 'rfnai3']::text[], 'rfnai3'),
  ('1a40162a-8a29-45f2-ad3e-2ad7f9076b4f'::uuid, ARRAY['1ucopx0', '1blk8en', '1fyzrxs', '1cmypwr']::text[], '1fyzrxs'),
  ('9a4e8363-058a-4df8-ac59-8cb14ace2af5'::uuid, ARRAY['kvxehn', 'bk8xu1', '14kq4em', 'e0lf4m']::text[], 'kvxehn'),
  ('523eaca7-363c-4a8b-8c77-aba3f38cda97'::uuid, ARRAY['tjik3r', 'e18nrc', 'lkcqgs', '1nqfabr']::text[], '1nqfabr'),
  ('65536e9b-6028-43dd-a458-986ec5980dad'::uuid, ARRAY['karzmw', '1pb3q5z', '88ddm5', '1abb1t6']::text[], '1abb1t6'),
  ('e631c3c4-bd73-4f35-ac5a-b0ed28e9920b'::uuid, ARRAY['l1ap2v', '1jct399', '3pbh0d', 'vn9jvy']::text[], 'l1ap2v'),
  ('999853ff-941a-4103-ad7d-baa7ed002989'::uuid, ARRAY['ga39m3', '17kbzfp', 'pryrk8', '14ke47e']::text[], 'ga39m3'),
  ('cc27e657-dfe9-45f5-8a45-3bac4000aa79'::uuid, ARRAY['f6knmo', 'd7qth', '1qrahv5', '1topak6']::text[], '1qrahv5'),
  ('090abdf9-704f-4b21-86c4-0fd8dcdd5e6a'::uuid, ARRAY['1mt1dc7', 's8iopn', '177w839', '1t9fqk7']::text[], '1t9fqk7'),
  ('8ac35c90-5b58-49a3-aba9-b479d776b1c2'::uuid, ARRAY['9wdvyj', 'kfzdv2', '5307fh', '1czeczw']::text[], '5307fh'),
  ('361afeeb-9da6-42bb-99c1-c9500f335676'::uuid, ARRAY['3vy81h', '3vy819', '1l99b8l', '1l99b7h']::text[], '1l99b7h'),
  ('469a19eb-5cc1-467c-909f-df228e8af4e3'::uuid, ARRAY['1qxo2n2', '164uy7d', 'nkff6q', 'yjxifj']::text[], '164uy7d'),
  ('e39b2e4e-823a-4262-bf5a-19f3e6414173'::uuid, ARRAY['1y0q0cp', '1vc1ey', 'i034e4', '11nxv1t']::text[], '1vc1ey'),
  ('fad3b4b7-1fcf-4553-a45f-835794d9d6b7'::uuid, ARRAY['mxbxgt', 'csaa4m', '1quvf1l', '4q0qpa']::text[], '4q0qpa'),
  ('104eb754-764b-4179-aea6-06ce4cee8ef2'::uuid, ARRAY['t3tc0z', '8207sq', '1caglzl', '8lihs3']::text[], '8lihs3'),
  ('a14899ca-3f2b-4c1f-8f21-053b566ac895'::uuid, ARRAY['yjqidu', '3tyx8o', '1h1519c', '1jac5g3']::text[], '1jac5g3'),
  ('cb3b4eb9-069c-4c77-a1b7-62198b22cfcb'::uuid, ARRAY['ijcags', '14ixpuu', '1v38byu', 'limlz2']::text[], '14ixpuu'),
  ('d3ad15bd-6d2a-4b1f-81ac-05a1dc11a782'::uuid, ARRAY['11oadus', 'b5r41e', 'rldc3z', '1pkieyn']::text[], 'rldc3z'),
  ('781802ca-0840-4eda-818a-61ad0d1439b6'::uuid, ARRAY['3kvosr', '3kvppr', '3kvoqx', '3kvoq0']::text[], '3kvosr'),
  ('77a080f4-a146-4b9d-8542-6d812e5a0751'::uuid, ARRAY['quv444', '449i4n', 'e5061h', '18xtmm8']::text[], '18xtmm8'),
  ('1c48b8cd-351f-40b8-b670-c25995295a4b'::uuid, ARRAY['1dgt6f2', '1xfpoeo', '1j0hd2l', '4n0xen']::text[], '4n0xen'),
  ('ef88a6fb-186a-4b4a-81f4-0d4a969bfe58'::uuid, ARRAY['e7wo9g', 'ddflgx', '1whb4tp', '1wmmcw1']::text[], 'ddflgx'),
  ('6561214e-5347-48b2-a24a-8fb89e1e526f'::uuid, ARRAY['zqrnpz', 'vhfrp8', '40nfbt', 'h40e6k']::text[], 'zqrnpz'),
  ('a78aa5e5-fe4a-42c1-8baa-e0978cc75b3f'::uuid, ARRAY['m3f276', 'm3f277', 'itnm80', 'm3f275']::text[], 'm3f275'),
  ('466ad666-5250-4954-a1f8-cdbfe053e02a'::uuid, ARRAY['1qp2596', '7k8d8r', '1ffqu6d', 'zsczvn']::text[], '1ffqu6d'),
  ('d4bacd82-699a-4019-bfcf-8a10ba4da400'::uuid, ARRAY['638v4v', 'ab6434', '1tcpw9c', 'chdfst']::text[], 'ab6434'),
  ('b145b192-3345-49ff-92d7-548ef01ab09d'::uuid, ARRAY['3w6rko', 'kfyqq0', 'py7pco', '3tyx8o']::text[], '3w6rko'),
  ('73a5eb55-8b21-4062-939a-af7a99872b02'::uuid, ARRAY['1u7v4em', '176a28q', '9wdvyj', '1qhautg']::text[], '1u7v4em'),
  ('8dd3a309-717e-4c58-9c86-1978cf00b7ae'::uuid, ARRAY['1mjivnd', '3u6f1o', '1ekxg5t', 'yk270c']::text[], '3u6f1o'),
  ('c4470f30-76bc-49a7-ae36-6b2106f23416'::uuid, ARRAY['lwciyp', 'oa6wso', '1aq8g17', '74to5y']::text[], 'oa6wso'),
  ('a5fec23e-0dfc-4e97-8793-5417a4c3cefd'::uuid, ARRAY['vh73bh', 'rivfb8', '1wdyhmo', '1d0a9mu']::text[], 'rivfb8'),
  ('9b2d9de6-7d29-42a6-a41a-183fc413c259'::uuid, ARRAY['1nl8aaz', '9wgqe9', '1rixbey', 'weihx7']::text[], '1nl8aaz'),
  ('c3907b4b-300f-4e3a-8eb9-95d2bc5cda50'::uuid, ARRAY['11qxuy8', '1hzxevc', '18xu0xk', '3o9ypw']::text[], '1hzxevc'),
  ('dd15b33b-fe01-4fdf-ae33-f4f9b7476ff8'::uuid, ARRAY['1ypdc65', '1gpzu6x', 'm9dt0e', '1moabhd']::text[], '1gpzu6x'),
  ('f2dfd78a-34c5-4998-920b-5bcd7fc5d14d'::uuid, ARRAY['qkn6is', 'ec7w2t', '1px6kiu', '42iura']::text[], 'ec7w2t'),
  ('6f0c1908-5acd-4385-974b-fc19bb8ac128'::uuid, ARRAY['174u8so', '3xgwdo', '1f1cc73', '1ey28b']::text[], '3xgwdo'),
  ('f8e6ab67-db2d-4025-afa5-343e19b455ec'::uuid, ARRAY['crtws6', '16wmzc8', '1ndj9ia', '27hajk']::text[], '16wmzc8'),
  ('960a48c1-e8f0-4f2b-ba5b-797b1b1ed0a6'::uuid, ARRAY['nqvopl', 'rrfxea', 'qqp116', 'e2s9dv']::text[], 'rrfxea'),
  ('34a2260a-c65c-4b74-9ab3-c91eb2293030'::uuid, ARRAY['1fkyun0', 'izs3vp', '1sgo4qk', '1rhckzu']::text[], 'izs3vp'),
  ('5589881e-e359-4f9c-8bf5-5bfa6c5f084c'::uuid, ARRAY['cdjrds', 'xbl0d9', '1m3m2aa', '1cn4rl2']::text[], 'xbl0d9'),
  ('b94be4a8-6b84-4fa9-ba5e-493442f0bcb6'::uuid, ARRAY['ou21ty', 'vkt0ms', '1t30qgz', '7pvxll']::text[], 'ou21ty'),
  ('8a6b8f7c-7973-47ec-852c-061a8ac24f48'::uuid, ARRAY['sd7fi8', '18atk3r', '1neiump', '1cdvqsi']::text[], '18atk3r'),
  ('2ab06ed9-454a-4f37-99e2-9b350158e51b'::uuid, ARRAY['7h5y6j', '1l9snie', 'jr3lj3', '6dzhil']::text[], 'jr3lj3'),
  ('f8940204-9923-452e-b233-c1df1d8528ff'::uuid, ARRAY['17pm3su', '4kljlr', '1ptiwk7', 'bfq0sa']::text[], '17pm3su'),
  ('8b09dcd8-2494-4283-8afe-c3f2298c6e0f'::uuid, ARRAY['nw1vc8', '7ulwf8', 'nj3dlq', 'efbb7x']::text[], '7ulwf8'),
  ('6860de18-3dcf-409c-8007-3e6387e7a440'::uuid, ARRAY['12w8qvc', 'hfwhb', '13by2zu', '15bftyo']::text[], '13by2zu'),
  ('ea9b4ba8-89a1-485e-ade6-9e7c51b0de96'::uuid, ARRAY['16r4t9w', '1xa2rte', '89gkzb', 'l5aedh']::text[], '1xa2rte'),
  ('a86e7155-6159-47be-828e-e85cdd51d175'::uuid, ARRAY['1fww16x', '1ejgbfk', '1v293e9', '1u7yof8']::text[], '1ejgbfk'),
  ('2e794dff-0cc9-4cb5-ba62-bc5e52abbade'::uuid, ARRAY['12elrw4', '1tqyurw', 'tz2vqu', '4reaov']::text[], '1tqyurw'),
  ('3ddac4c2-8df8-4afe-b607-a777089e5770'::uuid, ARRAY['u61c4s', '1tungcl', 'kme7y7', '7tkqjx']::text[], '1tungcl'),
  ('e06ed0ea-0a2c-4976-9be4-19ed707fed18'::uuid, ARRAY['a1o2g8', '1j8vgpr', '1cn6a7', 'gwat90']::text[], '1j8vgpr'),
  ('753735cb-b82e-4d7b-90b1-6050f56bf775'::uuid, ARRAY['11xnrhq', '3jhgvq', '1sytek0', '1fupt3u']::text[], '3jhgvq'),
  ('82fa7470-7f35-4cf1-acb3-cd88f54f147d'::uuid, ARRAY['84eqst', 's5875u', 'azzq2i', 'ksi6e2']::text[], 'ksi6e2'),
  ('f0e7bdeb-0905-4d77-8ce6-86afce370e53'::uuid, ARRAY['ujp8kh', '83b7va', '198ov36', '1kdre4y']::text[], '1kdre4y'),
  ('f6230b31-9f68-4be1-8d60-7e25d521f08a'::uuid, ARRAY['1vtltsl', '14djyqg', '2zoati', '15v02rb']::text[], '15v02rb'),
  ('f0c18192-e0c5-4124-a255-8bb476d759c0'::uuid, ARRAY['129ry8g', '1ieexee', '1ph8jul', 'es9zd0']::text[], '1ieexee'),
  ('2da83b5a-63e1-4a19-a486-ccd5ae0e5c83'::uuid, ARRAY['dg33ti', '1g9hx80', 'zv3i8x', 'ein0m7']::text[], 'zv3i8x'),
  ('c00ea18f-8194-4fb2-a996-3d416379cc3a'::uuid, ARRAY['l1lgdv', 'ggzfns', '18i559f', '1t2i75t']::text[], 'ggzfns'),
  ('1a892361-75b9-4f4d-b6ca-1a9d1e7e9518'::uuid, ARRAY['3055st', 'puuv7d', 'eppdw4', '3vody8']::text[], '3vody8'),
  ('29b6d154-d58c-457f-9856-7da873f2fdd0'::uuid, ARRAY['nz1xqj', '1q8j8zq', 'o0shhz', '18iteiy']::text[], 'o0shhz'),
  ('fbaea722-63f2-49ca-b1de-d23fb9c767b4'::uuid, ARRAY['o4io9v', '1lechg3', '1barn5v', 'iouy52']::text[], 'o4io9v'),
  ('125fe548-f8c4-4b12-a636-64770ba5d252'::uuid, ARRAY['4h64l7', 'dvt8t4', 'ygt7oo', 'wkp0av']::text[], 'wkp0av'),
  ('45d8ec14-0ee8-4624-aacf-7c5a4aa80b83'::uuid, ARRAY['1d8vjth', '16kbhwp', '1u8a2nf', '1gry9mr']::text[], '1gry9mr'),
  ('80577224-17d6-44bf-a551-9c55f1098f0c'::uuid, ARRAY['hnp3oc', 'ohh28p', '1qc9r2f', '1f7ahvw']::text[], 'ohh28p'),
  ('2ec6168c-a484-45b2-a0e5-694ea5aaca38'::uuid, ARRAY['1fvcprq', '905ysl', 'uwu32c', '1bj148s']::text[], '1fvcprq'),
  ('377fe5e0-1ee4-4938-bf8c-73d0faeb3155'::uuid, ARRAY['ww7jdw', '1gpzs7g', '1ata4h2', '1p35qf1']::text[], 'ww7jdw'),
  ('92ad2261-8c33-4a1a-91ae-4b36a0d0770f'::uuid, ARRAY['14cne06', '1dmzohi', 'm53hhc', 'a4nozk']::text[], '14cne06'),
  ('97d5b842-4c4b-4291-97e2-739e9a458c9c'::uuid, ARRAY['1wrkmcx', '1oesefr', 'juhord', 's6esz4']::text[], 's6esz4'),
  ('4b45d577-5dab-46c4-9420-7bb067116f0d'::uuid, ARRAY['1v85yyt', '1c7g0rj', 'x3rofk', 'qdbwtf']::text[], 'x3rofk'),
  ('adeb7c9b-ea4d-4e92-a06c-acb5655d3582'::uuid, ARRAY['10n4yay', '1vvf23q', '3tj6go', '1uaia53']::text[], '3tj6go'),
  ('b3081a08-e0e9-4a54-8c83-643daf59d816'::uuid, ARRAY['1c3f1tn', 'm4153', '1ysb94m', 'mdnrpg']::text[], 'mdnrpg'),
  ('d0bfdb55-087c-4659-9a84-14b4c92d4fbc'::uuid, ARRAY['1kx0059', '1cnrha5', 'rjcp72', 'jokzqj']::text[], 'jokzqj'),
  ('3c2ec160-0873-4cc2-ac1b-43b1c316fc78'::uuid, ARRAY['pjsmq6', '1ajxcjc', 't92haa', '12whrlg']::text[], 'pjsmq6'),
  ('01a6976f-a041-422f-aead-5e9ef106ad5b'::uuid, ARRAY['1l5728', 'zmiz1a', 'gnm8zw', 'e9xxbu']::text[], 'gnm8zw'),
  ('5ca3c99f-46f4-4538-9bc9-e369a52af865'::uuid, ARRAY['299zmb', '1jh59c2', '15qme88', 'fv327g']::text[], '299zmb'),
  ('550ee960-4520-47ee-ab62-c0459d2c8fdd'::uuid, ARRAY['95xhf8', 'ddmdu9', '144mnca', 'u0zj1d']::text[], 'ddmdu9'),
  ('7782dd37-de2a-4409-81b9-7dfaeb5709a0'::uuid, ARRAY['11ozoz', 't99hq2', 'a6s0rb', '11aqli1']::text[], 'a6s0rb'),
  ('c2df1a60-ae13-4ef5-8e26-e5605c8c35a3'::uuid, ARRAY['1p0ah1s', '2ak77u', '1we5ycy', '4c1jyf']::text[], '1p0ah1s'),
  ('867fcc90-5308-464b-ad95-755ea7712ba5'::uuid, ARRAY['zvnn2j', 'cz2uq3', '5bvr4j', 'pmoc7c']::text[], 'cz2uq3'),
  ('692def9b-6ae5-4040-a105-3c807e728c45'::uuid, ARRAY['sp0hjy', 'om399d', 'uzoe50', '15q39ol']::text[], 'uzoe50'),
  ('1b8c0be2-0f44-45b1-bd82-6c1de5f7cb30'::uuid, ARRAY['11t8lqq', '1nmyzmf', '1ron9ex', '13a6y9k']::text[], '13a6y9k'),
  ('17e36c25-310e-4277-8b68-04559a7b9a36'::uuid, ARRAY['nbdin1', 'mp9gh3', '1c4m49a', '1yn0ia6']::text[], '1c4m49a'),
  ('ac72e166-a8d4-4dd3-9bd5-7ef874b15d61'::uuid, ARRAY['10mh9qj', 'eovr6i', '1xfyoru', '16up56']::text[], '16up56'),
  ('10da44fc-b77d-4976-9feb-c99e56dd3db1'::uuid, ARRAY['376n7l', 'yjz63q', '376lh3', '3hnkc']::text[], 'yjz63q'),
  ('958e6f98-0dea-4d11-80e6-6e73117e3abd'::uuid, ARRAY['1njwvi1', '4kvyxm', '1tb8n9u', 'dz055y']::text[], '1tb8n9u'),
  ('667e0c77-d9da-4c9b-9b41-3fa33554388d'::uuid, ARRAY['1e38nrc', '1b9ku2n', 'o3mls1', 'w0zy2h']::text[], 'w0zy2h'),
  ('c04fab2d-3976-4676-a482-ad4a469b96a1'::uuid, ARRAY['1r1hgz9', 'cha5zp', '1a9gfaj', 'sqorue']::text[], '1a9gfaj'),
  ('ab2c430a-a593-4cfa-87e0-cf65251c951d'::uuid, ARRAY['1ggswvg', '13z5h2h', 'wxaryg', '21ngwz']::text[], '1ggswvg'),
  ('45491568-27a9-493b-aa98-bcd2646be640'::uuid, ARRAY['x01ur9', 'yxbuix', 'xyd2or', '1bzyvdf']::text[], 'x01ur9'),
  ('6c47dd54-6977-4501-b90b-09050855d9ed'::uuid, ARRAY['5agdoj', 's9dm84', '14xge3s', '12lwchy']::text[], '12lwchy'),
  ('de5d871c-8b0b-47c8-9108-4ee7d148c4db'::uuid, ARRAY['yjz7s8', 'yjz63q', '376lhx', '376lh3']::text[], '376lhx'),
  ('94464995-f520-44ec-8442-86ec002053d3'::uuid, ARRAY['376lh3', 'yjz7s8', '376lhx', 'yjz63q']::text[], '376lh3'),
  ('e6e9a483-566f-401a-ada7-07a79d27c8bd'::uuid, ARRAY['376lh3', '376lhx', 'yjz7s8', 'yjz63q']::text[], 'yjz7s8'),
  ('31e33fe8-fd92-4770-a8af-b04ea510cffe'::uuid, ARRAY['6l26ml', 'd3raq8', '1rj7dxv', 'ej0z0a']::text[], 'ej0z0a'),
  ('4ac95aea-b66f-4023-8a42-deea8feedcd7'::uuid, ARRAY['2nwhfw', '1m7a0tn', '1swihtf', 'y7670z']::text[], '1m7a0tn'),
  ('6b865c6b-e23b-45b4-96c7-1a32b924553f'::uuid, ARRAY['128kzyv', '1eviud3', '1t3jm3p', '1v0rsr0']::text[], '1v0rsr0'),
  ('ac3461fc-f5b3-4cc8-8751-5aa925f8b263'::uuid, ARRAY['cbcurq', '1jfgs2d', '1rd1oys', '6r7n7v']::text[], '6r7n7v'),
  ('d6e1aefb-e983-4743-bc3e-7f01e16694b7'::uuid, ARRAY['12w8e8o', 'p55i9b', 'f60aqf', 'nto23o']::text[], 'nto23o'),
  ('768b4371-20d1-4d78-a513-62a87271a78a'::uuid, ARRAY['1usw1na', '13ryskw', 'nd8ra2', '110nwzc']::text[], '13ryskw'),
  ('0b54fac9-3256-48a1-814c-c279df77331e'::uuid, ARRAY['97q0sl', '1ypddc9', '12z1b9e', '30gb8j']::text[], '97q0sl'),
  ('6e5bc2b5-6f63-4ec1-b25b-6f6b6aa6bf6b'::uuid, ARRAY['1rc2yq7', '1aqr5f4', '15vke7m', '1nu0ob7']::text[], '1aqr5f4'),
  ('1340a610-46c1-460b-bb41-5bb8a87f0939'::uuid, ARRAY['gmxva6', '89ef4p', 'kligaz', 'gj5tin']::text[], 'gj5tin'),
  ('1717afaf-d452-4508-883f-066dd2fd308c'::uuid, ARRAY['1it33wf', 'fningy', 'sv8f3s', '1urmksf']::text[], '1urmksf'),
  ('61acdb12-d498-4b50-937e-01a412204289'::uuid, ARRAY['1tocx', 'owdfi9', '1r76hx0', 'tpvu5j']::text[], 'tpvu5j'),
  ('3850aea0-b31b-4016-a44a-b6c2cf1cc83b'::uuid, ARRAY['kmra80', 'yjmrmb', '9ixxys', '1hwilgg']::text[], '9ixxys'),
  ('47f4e655-4e90-47d2-b5b0-c46edb55fcb0'::uuid, ARRAY['9ixxys', 'fy33jz', '1hwilgg', 'yjmrmb']::text[], 'yjmrmb'),
  ('cd7d8aab-ab40-4858-9530-f36988f996fe'::uuid, ARRAY['1tb4144', '1ldcvk4', '4de5am', 'l4r8l5']::text[], '4de5am'),
  ('3de313b0-d2a2-471e-a65d-b7db3c5338e4'::uuid, ARRAY['198m6uy', '10ny1lm', 'p7hmt6', 'p7hmt4']::text[], '10ny1lm'),
  ('4a24ae0f-aa4b-4ee0-aa71-0288cbb72497'::uuid, ARRAY['hsqrtm', '16rq10m', 'z507ke', '1buvc7w']::text[], '16rq10m'),
  ('f481b7c4-8489-4222-a583-4abd448d0d71'::uuid, ARRAY['jjsb99', 'n3izek', 'zlh208', 'pc3ba8']::text[], 'jjsb99'),
  ('c90068a7-ff3b-4202-b173-242a668eacea'::uuid, ARRAY['8lx5q2', '1ib2v1x', '12fwegb', '17yasba']::text[], '8lx5q2'),
  ('c6b3e1a2-d8f6-4771-9ac6-79c9bfc6f7cf'::uuid, ARRAY['ij1s2q', '1fcdpzn', '1fmmb6v', '1qt12m7']::text[], '1qt12m7'),
  ('cc8fab80-35b2-4133-b039-6316a276d81c'::uuid, ARRAY['f066ib', '6zbrss', 'bbxshp', 'hxcjwj']::text[], 'hxcjwj'),
  ('de5d9f51-d049-43dc-9f7e-3e15c9d86a31'::uuid, ARRAY['3lgzy9', 'a9roho', '7riocx', '1oxfz7w']::text[], 'a9roho'),
  ('cd99c5c6-71ad-452b-9129-5430b566e815'::uuid, ARRAY['jb9w6a', 'r4xz1g', '1ufv3wu', '12s8x0y']::text[], '12s8x0y'),
  ('0bfa6c1d-a6a1-4578-93ab-f473152cf4fb'::uuid, ARRAY['1hd1y6m', '1lp9x3e', '8a5t5b', '188uj50']::text[], '188uj50'),
  ('cf29b7c0-29f2-407d-83e5-630ea4074954'::uuid, ARRAY['us37aj', 'jye2am', '70shvc', 'h5mpwn']::text[], '70shvc'),
  ('509be8b8-e013-42d1-a896-aded1b84d08a'::uuid, ARRAY['e830f4', '1pm1h12', '1hfpce1', '1fa0zii']::text[], '1hfpce1'),
  ('4f0cd797-743c-484c-badf-0311a620f816'::uuid, ARRAY['1caunb3', '1qggvls', 'f1n592', 'pf9dzw']::text[], '1caunb3'),
  ('722c5b7a-7526-4d0b-afd0-40816b3751e5'::uuid, ARRAY['qa6lxm', '10y1iia', '1q23lp2', '19bsueb']::text[], 'qa6lxm'),
  ('41b3f6ef-fb6c-4688-8855-c60e84339b1f'::uuid, ARRAY['10kwca2', '1a2e3r4', 's9x91o', '1sw3gx5']::text[], '10kwca2'),
  ('5b83ce0d-b03b-4277-a0d6-3992e86f3b80'::uuid, ARRAY['89kw6s', '1tm11j0', '1hhzbt8', 'y0c2p0']::text[], '1tm11j0'),
  ('49a4ceb6-a556-4b94-80aa-bbda2a1d02d5'::uuid, ARRAY['u3726m', '1a5wwb4', '1hnsfxi', 'bgqsir']::text[], '1a5wwb4'),
  ('9352af75-17ad-4f9f-8aa1-1ee565066318'::uuid, ARRAY['7pm704', '17w41nx', 'eh5i0f', '1ebpfol']::text[], '17w41nx'),
  ('8c979cf3-184c-4bc5-b507-b2ea2e806bce'::uuid, ARRAY['x4lrkq', 'zvz8k6', '1f0holg', 'pf9dzw']::text[], 'zvz8k6'),
  ('27aca847-8d8d-4532-aad3-eb31d917d0ee'::uuid, ARRAY['1c93sul', 'idu813', 'zo1f3w', 'f0bx3k']::text[], 'idu813'),
  ('e6fc2f68-34fb-47ab-800e-321cc71eb437'::uuid, ARRAY['19pelkm', '1bzg43j', 'g54o0p', 'bgvqvc']::text[], '1bzg43j'),
  ('678bc04b-741b-4a14-9d17-4a7d514c32b1'::uuid, ARRAY['4848xv', '11her3n', 'c6dk9a', 'kimmz4']::text[], 'kimmz4'),
  ('649b4480-e766-4a76-a366-879e1c6346ef'::uuid, ARRAY['54r9ar', '1qqp629', 'd3llwm', 'hh8h1d']::text[], '54r9ar'),
  ('a6ac4582-e035-4350-8ba7-c503e4cf7175'::uuid, ARRAY['ee9pvg', 'fsb4y0', '1jbieds', 'b2eujo']::text[], 'fsb4y0'),
  ('6251fbd9-c90e-4323-a8c7-4f9e7a06b351'::uuid, ARRAY['1dsjtc1', '1705c7f', '1pv10su', '16hyq2f']::text[], '1705c7f'),
  ('5990bb7b-c801-42be-80bc-0df59f396e35'::uuid, ARRAY['1lfcstr', 'njoc3b', 'j4iakd', '1od0zoz']::text[], 'njoc3b'),
  ('fa4d458a-979b-4575-a873-b265f24b3cf5'::uuid, ARRAY['1gr532c', '657j3u', 'pc76m8', '1ufym68']::text[], 'pc76m8'),
  ('d1dc9e01-1e22-40e8-b970-76a5e2bf6de5'::uuid, ARRAY['1hwznlj', '1m0cvi6', '1lycoa8', '1yq46ih']::text[], '1lycoa8'),
  ('02c83bf8-693f-449e-b923-7e52b57d81e5'::uuid, ARRAY['1j8zxen', 'btdxj3', '17ezkc4', '1krpr64']::text[], '1j8zxen'),
  ('59a52781-9e3a-4cb1-9e7e-93d7130ba2d8'::uuid, ARRAY['c6idiw', '1wo8icz', '1kykvli', 'u35mkl']::text[], '1wo8icz'),
  ('036a8981-992e-4296-8ec2-8b105ee64ae2'::uuid, ARRAY['c6idiw', '1kykvli', 'u35mkl', 'eig04e']::text[], '1kykvli'),
  ('ab07751d-6798-4a2f-98b5-0aa8c9083263'::uuid, ARRAY['zwnii4', '4kacec', 'ujwzkv', 'hyvi1j']::text[], '4kacec'),
  ('205ff77e-404a-4705-85a3-c9b07c1d7353'::uuid, ARRAY['10tcly3', 'ju9zgc', '1vqezbo', '1kooyiv']::text[], 'ju9zgc'),
  ('ad8cdc34-9a0d-45ff-a3a8-cad3723c1836'::uuid, ARRAY['ggw930', '1adp08q', '1pv10su', '5tlax2']::text[], '1adp08q'),
  ('c3bdf7df-ac3f-429a-8b42-50d9103173f5'::uuid, ARRAY['8hls4s', 'nyegmz', '1y5ei1e', 'vf63fl']::text[], 'nyegmz'),
  ('3fede1bd-ddb1-485e-ad47-e87063cad0a5'::uuid, ARRAY['1m5epia', 'vjhlwh', 'gmyn4d', '10ghywx', '11fl08x']::text[], 'vjhlwh'),
  ('36219232-ee96-4d5a-9203-e02f900e0826'::uuid, ARRAY['p50uek', 'rk5a75', '1oi9b2e', 'ekehtd']::text[], '1oi9b2e'),
  ('ca7211c9-807d-4178-9fba-e3528d0519fe'::uuid, ARRAY['1tftqsi', '1g4rixi', '1c5u31a', 'yghu8a']::text[], '1tftqsi'),
  ('048dba74-4bfb-4cef-b379-16aa7d37f229'::uuid, ARRAY['mebwj', '1y1kbj6', 'x0b9fh', '1a24aox', 'r19qd4']::text[], '1a24aox'),
  ('08222345-48da-4fe2-83d1-d66a5235cfc8'::uuid, ARRAY['19d5u6n', '136b2qu', '1ov9zij', '2dli1a']::text[], '19d5u6n'),
  ('aaa0629f-e234-4929-beeb-ff7b273e51e6'::uuid, ARRAY['1ojqyyd', '1ndyczi', '1cpuauj', 'vr01ry']::text[], '1cpuauj'),
  ('6583b335-5020-4f63-82a5-2fc6c4f4d91d'::uuid, ARRAY['yj87ja', '3t1x', '3hmpv', '3hmpw']::text[], 'yj87ja'),
  ('8b0e8afe-ce32-4442-bac6-587822783ad3'::uuid, ARRAY['15e2x4g', 'z7qhxx', '1ihehs', '45ilb6']::text[], 'z7qhxx'),
  ('4742c194-88b0-4b37-937a-1496174c2ae7'::uuid, ARRAY['t2r2d2', 'gkdae2', '13bf1of', '107q8ew']::text[], '13bf1of'),
  ('2dd765ac-1d94-44cc-a187-609d81005443'::uuid, ARRAY['1d48wbe', 'vizo9j', '1om2usx', '1u2fdbt']::text[], '1om2usx'),
  ('6e61478e-7562-4076-be2a-2d7d909cd1e4'::uuid, ARRAY['3sd4v3', '5n1837', '1d92z6p', 'k4dwys']::text[], '1d92z6p'),
  ('a063f8fd-8999-4f7f-97be-62613d3613ee'::uuid, ARRAY['148jev1', '18c1un3', '1nua3g7', 'dgnu44']::text[], 'dgnu44'),
  ('eb2aab64-db49-4325-b859-fb4aa3dbeddf'::uuid, ARRAY['fc3yfo', 'fgn62r', '1mpqvlj', '1fvcprq', '1e98rg7']::text[], '1mpqvlj'),
  ('795bafdd-f5c8-49fb-8451-f6f5714ff2dd'::uuid, ARRAY['sj78iz', 'ae4i8m', 'lnu7gd', '10yoty9', '14qnf9s']::text[], '10yoty9'),
  ('4c81ee23-2458-406c-ac62-6738596740fe'::uuid, ARRAY['o4mrj9', '376fdt', '1xcak2n', 'yjr5ys']::text[], 'o4mrj9'),
  ('2c1b97a6-32bd-4c00-988f-00646e4a1aeb'::uuid, ARRAY['16y9gl9', '9nh2j9', '1epk8k0', 'kco5ue']::text[], '16y9gl9'),
  ('3c0ccdf2-15e8-46cc-805a-ee15f5fa9d4c'::uuid, ARRAY['5zhr7a', 'cfdbdw', '1ps3bgw', '1wi0cs7']::text[], '5zhr7a'),
  ('65eebf21-c713-4520-94f6-ef0d8f18dde3'::uuid, ARRAY['11wzdzf', '1djjhqa', '1qnmatb', 'vjlj2t']::text[], '1djjhqa'),
  ('c800af59-e11f-4cbd-92c0-d556078709fc'::uuid, ARRAY['h0q270', '8wxj3v', '299tio', 'wtae8g']::text[], '299tio'),
  ('b2406382-c1b3-4d55-abe5-be143f9cdced'::uuid, ARRAY['s37g62', '1c09qkl', '112vz66', '7qou2s']::text[], 's37g62'),
  ('b7211d88-1621-433e-992d-8d087a8a7a5d'::uuid, ARRAY['1d9cosw', '8cw9xi', '197xe7o', 'xyba95']::text[], '1d9cosw'),
  ('73574ea6-2036-4028-9b07-86be647e838d'::uuid, ARRAY['174ux2s', '17fd49x', '120tx6', 'hsgdfp']::text[], '17fd49x'),
  ('caa83f84-f75b-4ebe-940a-01048d6fca81'::uuid, ARRAY['jy5ka5', 'zudlpd', '1l0p317', 'ib3aqo']::text[], '1l0p317'),
  ('9760671b-de49-4bf5-8965-0d49b52abc19'::uuid, ARRAY['1lxmivb', 'bk8uml', 'mknv17', '1ji92ej', '14zl945']::text[], 'mknv17'),
  ('38f9a36f-c887-4ca9-a929-0874822d61df'::uuid, ARRAY['1ufq8vq', '1lbusm4', '1m4qgir', 'mp9ep4']::text[], '1lbusm4')
) as v(id, option_ids, correct_option_id)
where q.id = v.id;

-- 3. "Enfermedades desmielinizantes SNA 2023" lives only in the repo; create it.
insert into academy_quizzes (id, title, description, time_limit_minutes, passing_score, shuffle_questions, show_correct_answers, status, created_by)
values ('f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Enfermedades desmielinizantes SNA 2023', 'Examen de 25 preguntas sobre esclerosis múltiple, NMOSD, MOGAD, diagnóstico, tratamiento y manejo sintomático.', 40, NULL, false, true, 'published', 'repo-sync')
on conflict (id) do nothing;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('bd318faa-88a2-4fce-b01e-02ef8d2eda5f', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Respecto a los anticuerpos anti-acuaporina-4 (AQP4-IgG), ¿cuál de las siguientes afirmaciones es correcta?', 'multiple_choice', ARRAY['Reconocen un epítopo intracelular de la acuaporina-4.', 'Los ensayos ELISA son el método de mayor sensibilidad diagnóstica.', 'El método de elección para su detección es el Cell-Based Assay (CBA).', 'Su positividad confirma esclerosis múltiple.']::text[], 2, ARRAY['qjuhi', '183dxb8', 'jkh1ii', '1fl43dj']::text[], 'jkh1ii', 'AQP4-IgG debe buscarse en suero mediante un ensayo basado en células (CBA), que conserva los epítopos extracelulares y conformacionales de la acuaporina-4. Los ensayos ELISA tienen menor sensibilidad y pueden dar falsos positivos, sobre todo con títulos bajos.

La positividad, en un cuadro clínico compatible, identifica NMOSD AQP4 positivo, no esclerosis múltiple. El anticuerpo suele ser una IgG1 que se une a la acuaporina-4 de los pies astrocitarios, activa el complemento y produce una astrocitopatía; el daño de oligodendrocitos y la desmielinización son secundarios.

Referencia: Wingerchuk DM et al. International consensus diagnostic criteria for neuromyelitis optica spectrum disorders. Neurology. 2015;85:177-189.', 1, 0)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('001cd673-1fd6-49c0-8392-d7057bbab7f3', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de las siguientes características de la mielitis es más sugestiva de NMOSD que de esclerosis múltiple?', 'multiple_choice', ARRAY['Lesión medular periférica menor de un segmento.', 'Mielitis longitudinalmente extensa (≥3 segmentos vertebrales).', 'Recuperación clínica completa en la mayoría de los pacientes.', 'Predominio de lesiones dorsolaterales cervicales.']::text[], 1, ARRAY['34b7q0', '14xofl7', '1vo5t7w', 'yuufsp']::text[], '14xofl7', 'La mielitis longitudinalmente extensa, definida por una lesión que abarca al menos tres segmentos vertebrales, es un patrón característico de NMOSD. Suele ser central, comprometer gran parte del área transversal de la médula y dejar secuelas importantes.

Las lesiones medulares de esclerosis múltiple suelen ser cortas, periféricas, laterales y ocupar menos de la mitad del área axial. MOGAD también puede producir mielitis longitudinalmente extensa, en especial con afectación del cono o signo de la H. Una lesión corta no excluye NMOSD: puede verse al comienzo del ataque o después de que una lesión extensa se fragmente con el tratamiento.', 1, 1)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('e97a9796-93b5-4d7b-a191-808eeb9070d1', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Una mujer de 35 años consulta por neuritis óptica grave unilateral y mielitis longitudinalmente extensa. El Cell-Based Assay resulta positivo para AQP4-IgG. ¿Cuál de las siguientes terapias cuenta con evidencia de un ensayo clínico pivotal específico para reducir el riesgo de recaídas en esta enfermedad?', 'multiple_choice', ARRAY['Interferón beta.', 'Fingolimod.', 'Inebilizumab.', 'Acetato de glatiramer.']::text[], 2, ARRAY['16ppdkf', '12lvx2z', 'twyk0e', '1c7gp1h']::text[], 'twyk0e', 'Inebilizumab es un anticuerpo monoclonal anti-CD19 que depleciona una franja amplia de la línea B, incluidas células implicadas en la producción de AQP4-IgG. En N-MOmentum redujo de manera marcada el riesgo de nuevos ataques frente a placebo, con mayor claridad en pacientes AQP4-IgG positivos.

Interferón beta, fingolimod y acetato de glatiramer son tratamientos de esclerosis múltiple; no previenen adecuadamente las recaídas de NMOSD y algunos pueden agravarla. Otros tratamientos con ensayos específicos en NMOSD AQP4 positivo son eculizumab, que inhibe el complemento, y satralizumab, que bloquea la señalización de IL-6.

N-MOmentum fue publicado formalmente como un ensayo fase 2/3, no como fase III pura. Referencia: Cree BAC et al. Lancet. 2019;394:1352-1363.', 1, 2)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('94ba56dd-79f2-4c94-8708-09e4f3a7ebcd', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Un paciente de 28 años consulta por una neuritis óptica típica. La RM demuestra diseminación en el espacio, pero no diseminación en el tiempo. El LCR presenta bandas oligoclonales patrón tipo 2. ¿Cuál es la interpretación correcta según la revisión de los criterios de McDonald 2024?', 'multiple_choice', ARRAY['Las bandas oligoclonales sólo aportan valor pronóstico.', 'Es necesario esperar una segunda recaída para confirmar EM.', 'Las bandas oligoclonales pueden sustituir la demostración de diseminación en el tiempo.', 'Debe repetirse la RM a los 6 meses antes de establecer el diagnóstico.']::text[], 2, ARRAY['6tlvqt', '1p6u0rp', '1a3u3tb', '1ne1pwr']::text[], '1a3u3tb', 'Las bandas oligoclonales restringidas al LCR, patrón tipo 2, demuestran síntesis intratecal de IgG. En un síndrome clínico típico que ya cumple diseminación en el espacio, permiten establecer el diagnóstico sin esperar una segunda recaída o una nueva lesión en la RM.

La revisión 2024 incorporó el nervio óptico como quinta topografía, aceptó el índice de cadenas livianas kappa como alternativa a las bandas y sumó marcadores de especificidad como el signo de la vena central y las lesiones con anillo paramagnético. Ningún biomarcador reemplaza la necesidad de un cuadro compatible y de excluir una explicación mejor.

Referencia: Montalban X et al. Diagnosis of multiple sclerosis: 2024 revisions of the McDonald criteria. Lancet Neurol. 2025.', 1, 3)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('c0f0afdf-b0f2-4277-8df8-7ccc137d8705', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de las siguientes situaciones representa una bandera roja que debería hacer reconsiderar el diagnóstico de esclerosis múltiple antes de aplicar los criterios de McDonald?', 'multiple_choice', ARRAY['Neuritis óptica unilateral con buena recuperación.', 'Síndrome de tronco encefálico típico.', 'Síndrome de área postrema con náuseas, vómitos e hipo persistentes.', 'Mielitis parcial con predominio sensitivo.']::text[], 2, ARRAY['6p8fre', '1jkn9qj', '1rx3fp0', '1bauend']::text[], '1rx3fp0', 'El síndrome de área postrema se presenta con hipo, náuseas o vómitos persistentes sin otra explicación. Es una manifestación central de NMOSD, relacionada con la elevada expresión de acuaporina-4 en el bulbo dorsal.

Una neuritis óptica unilateral dolorosa, una mielitis parcial sensitiva y determinados síndromes focales de tronco son presentaciones típicas de esclerosis múltiple. Los criterios de McDonald no diferencian EM de sus imitadores: se aplican después de comprobar que el síndrome es compatible. Ante un síndrome de área postrema corresponde solicitar AQP4-IgG en suero mediante CBA y revisar la RM del bulbo antes de indicar una terapia para EM.', 1, 4)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('e0e1d001-ca58-431e-a0f1-9aefc02f6b42', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de las siguientes afirmaciones define correctamente una recaída de esclerosis múltiple?', 'multiple_choice', ARRAY['Los síntomas deben durar al menos 12 horas.', 'Puede diagnosticarse durante una infección sistémica si la RM es compatible.', 'Debe corresponder a un episodio inflamatorio desmielinizante del SNC de al menos 24 horas de duración y sin fiebre ni infección.', 'Siempre requiere recuperación clínica completa.']::text[], 2, ARRAY['tpekf2', '15ylbdx', '1d6bl02', '1cqhzmi']::text[], '1d6bl02', 'Una recaída es un episodio neurológico nuevo o un empeoramiento atribuible a inflamación desmielinizante del SNC, de al menos 24 horas, sin fiebre, infección ni otra causa metabólica. La recuperación puede ser completa o dejar secuelas.

Los síntomas paroxísticos duran segundos o minutos, pero pueden contar como recaída si se repiten durante un período total de al menos 24 horas. Para considerar dos brotes separados suele exigirse un intervalo aproximado de 30 días. La reaparición de déficits antiguos durante una infección o con aumento de temperatura es una pseudorrecaída y no implica necesariamente actividad inflamatoria nueva.', 1, 5)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('0b8bfda5-40fb-467c-99d5-c6bb89ffc467', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de las siguientes afirmaciones respecto a la neuritis óptica típica de esclerosis múltiple es correcta?', 'multiple_choice', ARRAY['Habitualmente es bilateral y presenta edema de papila marcado.', 'Generalmente es unilateral, dolorosa con los movimientos oculares y presenta buena recuperación funcional.', 'Se caracteriza por pérdida visual severa menor de 20/200 y mala recuperación.', 'Se acompaña frecuentemente de exudados retinianos.']::text[], 1, ARRAY['1p5b9o', '1k67381', 'y8ho01', 'xgaq8a']::text[], '1k67381', 'La neuritis óptica típica de esclerosis múltiple es unilateral, subaguda, dolorosa con los movimientos oculares y suele causar un escotoma central con discromatopsia. El fondo de ojo puede ser normal porque la inflamación suele ser retrobulbar, y la recuperación funcional habitualmente es buena.

El patrón ayuda al diagnóstico diferencial. NMOSD AQP4 positivo suele comprometer el segmento posterior y el quiasma, con pérdida grave y recuperación pobre. MOGAD afecta con mayor frecuencia el segmento anterior, puede ser bilateral y produce edema papilar marcado, exudados y realce de la grasa perineural. Una neuritis bilateral simultánea es atípica para EM.', 1, 6)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('d2f08cae-bac0-466b-a4b0-a0afab46b497', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Respecto a la mielitis asociada a MOGAD, ¿cuál de las siguientes afirmaciones es correcta?', 'multiple_choice', ARRAY['La afectación del cono medular es una característica sugestiva de MOGAD.', 'La recuperación funcional suele ser peor que en NMOSD.', 'Las lesiones medulares son habitualmente menores de un segmento vertebral.', 'Los síntomas esfinterianos son excepcionales.']::text[], 0, ARRAY['1t15o31', 'hidzuo', '173mcyg', '18pj5mo']::text[], '1t15o31', 'La afectación del cono medular es un rasgo sugestivo de MOGAD y explica la frecuencia de disfunción vesical, intestinal y sexual. Otros patrones de apoyo son la mielitis longitudinalmente extensa y el signo de la H en el corte axial, producido por el compromiso predominante de la sustancia gris.

MOGAD también puede causar lesiones cortas, por lo que la longitud aislada no establece el diagnóstico. La recuperación motora suele ser mejor que en NMOSD AQP4 positivo, aunque pueden persistir secuelas esfinterianas o sexuales. El diagnóstico requiere un evento compatible, MOG-IgG en suero mediante CBA y ausencia de una explicación alternativa.

Referencia: Banwell B et al. Diagnosis of MOG antibody-associated disease: International MOGAD Panel proposed criteria. Lancet Neurol. 2023;22:268-282.', 1, 7)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('e0c53342-ed17-42a2-a412-ad02f6c0b954', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Un paciente presenta un primer episodio de ADEM con anticuerpos anti-MOG positivos. ¿Cuál de las siguientes afirmaciones es la más adecuada?', 'multiple_choice', ARRAY['Todos los pacientes evolucionarán a una enfermedad recurrente.', 'La persistencia de anticuerpos anti-MOG predice con certeza una evolución recurrente.', 'Debe iniciarse indefinidamente inmunoterapia de mantenimiento en todos los casos.', 'MOGAD puede ser monofásica o recurrente, por lo que el seguimiento clínico es fundamental.']::text[], 3, ARRAY['b6l0uj', '4pxvsx', 'khozha', 'fi0umn']::text[], 'fi0umn', 'MOGAD puede seguir un curso monofásico o recurrente. En la infancia, ADEM es una forma frecuente de presentación, pero un primer episodio anti-MOG positivo no permite anticipar con certeza la evolución. La persistencia de títulos altos aumenta la sospecha de recurrencia, sin determinarla por sí sola.

El ataque agudo se trata con corticoides y un descenso cuidadoso. La inmunoterapia prolongada se individualiza y tiene mayor fundamento después de una segunda recaída, ante un ataque muy grave con mala recuperación o cuando aparecen recaídas al reducir los corticoides. El seguimiento debe incluir evolución clínica, función cognitiva, RM seriada e interpretación contextual de MOG-IgG.', 1, 8)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('4928ae4c-96fd-4595-8312-d7cae90ceaac', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Respecto al estudio del líquido cefalorraquídeo, ¿cuál de los siguientes hallazgos constituye una bandera roja para esclerosis múltiple?', 'multiple_choice', ARRAY['Bandas oligoclonales aisladas en LCR.', 'Pleocitosis marcada, mayor de 50 células/mm³.', 'Índice IgG elevado.', 'Síntesis intratecal de IgG.']::text[], 1, ARRAY['71a6t9', '128tynp', '1q1gwe2', '4nd9m8']::text[], '128tynp', 'En esclerosis múltiple puede haber una pleocitosis linfocitaria leve, pero un recuento mayor de 50 células/mm³ es una bandera roja. Obliga a investigar infecciones, neurosarcoidosis, vasculitis, neoplasias hematológicas y otras enfermedades inflamatorias. También son atípicos el predominio de neutrófilos, la hiperproteinorraquia o hipoglucorraquia marcadas y las bandas en espejo entre suero y LCR.

Las bandas oligoclonales restringidas al LCR y la síntesis intratecal de IgG apoyan el diagnóstico, aunque no son patognomónicas. El índice IgG puede elevarse, pero es menos sensible y específico que las bandas. Los criterios de McDonald 2024 también aceptan el índice de cadenas livianas kappa como alternativa para demostrar inflamación intratecal.', 1, 9)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('ef3db973-916e-4d7b-a7bb-d984c07fc784', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿La infección previa por cuál de los siguientes virus ha mostrado una asociación significativa con un riesgo aumentado de esclerosis múltiple?', 'multiple_choice', ARRAY['Enterovirus D68.', 'Citomegalovirus (CMV).', 'Herpes simplex virus (HSV).', 'Parvovirus B19.', 'Epstein-Barr virus (EBV).']::text[], 4, ARRAY['4i7iuj', '1d36eiv', '1jnvth3', '1rgxm68', '4wx7l2']::text[], '4wx7l2', 'La infección por Epstein-Barr virus es el factor infeccioso con la asociación más sólida con esclerosis múltiple. En una cohorte de más de diez millones de militares estadounidenses, el riesgo aumentó 32 veces después de la seroconversión para EBV, sin un aumento comparable tras la infección por CMV.

EBV no es suficiente para causar EM: infecta a la gran mayoría de la población y sólo una pequeña proporción desarrolla la enfermedad. Los mecanismos propuestos incluyen mimetismo molecular, alteración de la barrera hematoencefálica y persistencia del virus en células B autorreactivas.

Referencia: Bjornevik K et al. Longitudinal analysis reveals high prevalence of Epstein-Barr virus associated with multiple sclerosis. Science. 2022;375:296-301. doi:10.1126/science.abj8222.', 1, 10)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('abdc86b3-d148-42a0-ac03-129416b11461', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Una mujer de 42 años con EMRR consulta por infección urinaria y fiebre de 39,5 °C. La debilidad y la espasticidad ya conocidas en ambos miembros inferiores empeoraron durante las últimas 36 horas. ¿Cuál es la interpretación más probable?', 'multiple_choice', ARRAY['Debe solicitarse un EMG.', 'Presenta EM progresiva y debe retirarse el interferón.', 'Presenta una recaída y debe recibir antibióticos y corticoides.', 'Probablemente presenta una pseudorrecaída.']::text[], 3, ARRAY['czocqp', '1hx6h1w', '1p6phnw', 't4sxs8']::text[], 't4sxs8', 'La reaparición o intensificación de déficits conocidos durante una infección febril corresponde probablemente a una pseudorrecaída. El aumento de temperatura empeora transitoriamente la conducción en axones desmielinizados, sin implicar una nueva lesión inflamatoria.

La conducta inicial es tratar la infección, controlar la fiebre y reevaluar. No corresponde diagnosticar progresión, retirar la terapia modificadora ni indicar corticoides de manera automática. Una infección y una recaída verdadera pueden coexistir; si aparecen síntomas completamente nuevos o el deterioro persiste después de resolver la intercurrencia, debe reconsiderarse un brote.', 1, 11)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('3aadf604-2a9b-4568-8967-0f5a3641b592', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Un paciente con EM secundaria progresiva camina con andador y aumenta su espasticidad de leve a moderada o grave en 48 horas, hasta impedirle la deambulación. ¿Cuál es la primera conducta?', 'multiple_choice', ARRAY['Aumentar la dosis de antiespásticos orales.', 'Incrementar las sesiones de kinesiología.', 'Descartar una intercurrencia clínica.', 'Aplicar toxina botulínica.']::text[], 2, ARRAY['1eyv0l4', 'yg43mn', '1dcgm6d', 'ddht5c']::text[], '1dcgm6d', 'Un aumento abrupto de la espasticidad obliga a buscar una causa desencadenante antes de modificar el tratamiento. Las causas frecuentes incluyen infección urinaria, fiebre, retención vesical, constipación, dolor, lesiones cutáneas, mala postura y exposición al calor.

Aumentar antiespásticos sin evaluar la causa puede producir debilidad, sedación y caídas. La toxina botulínica se reserva para patrones focales persistentes; no es la respuesta inicial a un deterioro generalizado en 48 horas. Resuelta la intercurrencia, la espasticidad basal se reevalúa y se define un plan funcional con rehabilitación, tratamiento oral o intervenciones focales.', 1, 12)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('a87745b1-b7b5-4a7f-99f1-24db9fa31928', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Todas las siguientes drogas se utilizan como tratamiento preventivo en pacientes con MOGAD, excepto:', 'multiple_choice', ARRAY['Micofenolato.', 'Azatioprina.', 'Inmunoglobulina intravenosa.', 'Interferón beta.']::text[], 3, ARRAY['vjfdpv', '1xdojf9', 'tm3prk', '16ppdkf']::text[], '16ppdkf', 'Interferón beta es una terapia para esclerosis múltiple que no previene adecuadamente las recaídas de MOGAD y puede ser perjudicial. También deben evitarse otras extrapolaciones automáticas desde EM, como acetato de glatiramer, teriflunomida, dimetilfumarato y natalizumab.

Micofenolato, azatioprina e inmunoglobulina intravenosa se utilizan como tratamientos de mantenimiento en MOGAD recurrente. La evidencia no es equivalente entre ellos y proviene en gran parte de cohortes observacionales. La decisión de iniciar tratamiento prolongado depende del número y gravedad de los ataques, la recuperación, la dependencia de corticoides, la edad y las comorbilidades.', 1, 13)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('9460a3fd-588c-4690-841e-f5feebdb54c5', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Respecto al curso del embarazo en la esclerosis múltiple, ¿cuál de las siguientes afirmaciones es correcta?', 'multiple_choice', ARRAY['Es siempre un embarazo de alto riesgo.', 'Existe un aumento definido del riesgo de aborto espontáneo y parto pretérmino por la enfermedad en sí misma.', 'La esclerosis múltiple per se no condiciona un embarazo de alto riesgo.', 'La esclerosis múltiple aumenta por sí misma el riesgo de malformaciones congénitas.']::text[], 2, ARRAY['m3asvq', '1xyzeqw', 'xd9ziu', '1bzq5tu']::text[], 'xd9ziu', 'La esclerosis múltiple por sí sola no obliga a clasificar el embarazo como de alto riesgo y no es una enfermedad teratogénica. El riesgo individual depende de la discapacidad, la actividad inflamatoria, las comorbilidades y la exposición a tratamientos.

La actividad de la EM suele disminuir durante la gestación, con un mínimo en el tercer trimestre, y aumentar durante los primeros meses posparto. La planificación debe incluir estabilidad previa, selección de una terapia compatible y prevención del rebote al suspender fármacos de alta eficacia. Algunos estudios observacionales recientes describen asociaciones modestas con resultados obstétricos adversos, pero no demuestran que la EM aislada sea la causa; la evaluación sigue siendo individual.', 1, 14)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('09cae5c4-258e-4e8d-beee-309203918d13', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuánto tiempo de enfermedad estable y bajo tratamiento se recomienda, como mínimo, antes de planificar el embarazo en una paciente con EM de baja actividad?', 'multiple_choice', ARRAY['Al menos 1 año.', 'Al menos 5 años.', 'Al menos 6 meses.', 'No se hace ninguna recomendación.']::text[], 0, ARRAY['1qvbn9w', 't7xauj', '14eoqk5', '17677no']::text[], '1qvbn9w', 'En una paciente con baja actividad y factores pronósticos favorables se recomienda al menos un año de estabilidad clínica y radiológica bajo tratamiento antes de intentar el embarazo. Si la enfermedad es activa, el período recomendado aumenta a dos años.

La estabilidad no se define sólo por el paso del tiempo: deben revisarse las recaídas, la recuperación, la RM, el tratamiento utilizado y su eventual período de lavado o riesgo de rebote. La edad materna y la reserva ovárica también condicionan la decisión, por lo que no debe postergarse el tratamiento ni la planificación sin una evaluación individual.', 1, 15)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('fb8aa354-b73e-48b0-bc5c-a230967f8348', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de los siguientes parámetros no forma parte del NEDA-3?', 'multiple_choice', ARRAY['La actividad en la RM convencional.', 'Las recaídas clínicas.', 'La progresión de la discapacidad.', 'La atrofia cerebral en RM.']::text[], 3, ARRAY['1t6gmo7', 'ilj9ct', 'k1jr8s', '1088b94']::text[], '1088b94', 'NEDA-3 exige ausencia de recaídas, ausencia de progresión confirmada de la discapacidad y ausencia de actividad en RM, definida por lesiones T2 nuevas o aumentadas y lesiones captantes de gadolinio. La atrofia cerebral no forma parte de esos tres dominios; se agrega en NEDA-4.

NEDA-3 está orientado sobre todo a la inflamación focal y puede no detectar PIRA, deterioro cognitivo, lesiones corticales o inflamación compartimentalizada. La medición individual de volumen cerebral también tiene limitaciones por variabilidad técnica, hidratación, envejecimiento y pseudoatrofia después de iniciar un tratamiento eficaz.

Referencia: Kappos L et al. Inclusion of brain volume loss in a revised measure of no evidence of disease activity (NEDA-4). Mult Scler. 2016;22:1297-1305.', 1, 16)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('144b975c-bb6f-4a90-afe9-c46149d4cfe9', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Qué significa el refuerzo con gadolinio de una placa desmielinizante?', 'multiple_choice', ARRAY['Es un signo de actividad inflamatoria de la enfermedad.', 'Está directamente relacionado con la discapacidad.', 'Es un signo específico de EM secundaria progresiva.', 'Siempre se transforma en un agujero negro.', 'Todas son correctas.']::text[], 0, ARRAY['1h13hfc', '12xgxfx', '1412pk8', '14hzivv', '6zyb1g']::text[], '1h13hfc', 'El realce con gadolinio indica alteración activa de la barrera hematoencefálica y permite reconocer la fase inflamatoria reciente de una lesión. No es específico de esclerosis múltiple y debe interpretarse junto con la morfología, la localización y el contexto clínico.

El realce suele ser transitorio. Si persiste durante más de tres meses, debe reconsiderarse el diagnóstico y buscar vasculitis, neoplasia, sarcoidosis u otra causa. No toda lesión captante evoluciona a un agujero negro. Los agujeros negros son lesiones hipointensas en T1 que reflejan daño tisular más permanente, gliosis y pérdida axonal, y tienen una relación más estrecha con discapacidad que el realce transitorio.', 1, 17)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('ede6032f-a7aa-47af-beab-6ef5640c4917', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de las siguientes drogas modificadoras de la enfermedad es considerada una terapia de reconstitución inmune?', 'multiple_choice', ARRAY['Alemtuzumab.', 'Fingolimod.', 'Dimetilfumarato.', 'Ninguna de ellas.']::text[], 0, ARRAY['17a2e1m', '12lvx2z', 'bj673u', '1o4wx0d']::text[], '17a2e1m', 'Alemtuzumab produce una depleción profunda de linfocitos T y B seguida de repoblación inmunitaria. Se administra en cursos breves con un efecto que puede persistir sin tratamiento continuo. Cladribina comparte este concepto de reconstitución inmune pulsada.

Fingolimod y dimetilfumarato son terapias de mantenimiento: requieren administración diaria para sostener su efecto. La clasificación no es completamente uniforme; algunas revisiones utilizan una definición más amplia para otras terapias depletoras. En el uso clínico habitual, alemtuzumab y cladribina son los ejemplos farmacológicos prototípicos de reconstitución inmune.', 1, 18)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('89b9cfa8-4363-46b3-845a-2c4b376d6482', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál afirmación es correcta respecto a la fisiopatología de NMOSD AQP4 positivo?', 'multiple_choice', ARRAY['La neurona permanece siempre indemne.', 'La desmielinización es un fenómeno secundario al daño astrocitario.', 'La barrera hematoencefálica permanece intacta.', 'Nunca se activa el sistema del complemento.']::text[], 1, ARRAY['12uzan1', '18syc9g', 'rwifnw', 'v4kn93']::text[], '18syc9g', 'NMOSD AQP4 positivo es una astrocitopatía primaria. AQP4-IgG entra al SNC a través de una barrera hematoencefálica alterada, se une a los pies astrocitarios y activa el complemento. La lesión atrae neutrófilos y eosinófilos y produce muerte del astrocito; la desmielinización, el daño axonal y la pérdida neuronal aparecen de forma secundaria.

La destrucción astrocitaria también reduce el transportador EAAT2, favoreciendo acumulación de glutamato y excitotoxicidad. Esta secuencia explica la eficacia de tratamientos dirigidos a la línea B, IL-6 o complemento y diferencia a NMOSD de la esclerosis múltiple, donde el blanco inicial no es el astrocito.', 1, 19)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('8f79ca43-96db-4dbc-94cd-f24d874b2dce', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Respecto a la fatiga en esclerosis múltiple, ¿cuál debe ser el primer paso antes de indicar un tratamiento farmacológico?', 'multiple_choice', ARRAY['Iniciar amantadina.', 'Solicitar polisomnografía en todos los pacientes.', 'Identificar y tratar causas secundarias de fatiga.', 'Indicar modafinilo.']::text[], 2, ARRAY['xhdku8', '1ki249d', '1h12w1v', '154hr8v']::text[], '1h12w1v', 'La evaluación comienza por buscar causas secundarias: depresión, trastornos del sueño, nocturia, espasmos nocturnos, dolor, anemia, hipotiroidismo, infecciones y efectos adversos de medicamentos. La polisomnografía se reserva para una sospecha concreta, como apnea o movimientos periódicos de las piernas.

El tratamiento inicial combina ejercicio aeróbico adaptado, conservación de energía, descansos breves programados, terapia ocupacional y, cuando corresponde, intervenciones cognitivo-conductuales. Amantadina y modafinilo pueden probarse en casos seleccionados, pero la evidencia es limitada e inconsistente; no sustituyen la corrección de una causa reversible.', 1, 20)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('f521c34a-9898-4d0b-b91a-4b9d1997cdb3', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'En un paciente con vejiga hipoactiva secundaria a esclerosis múltiple, ¿cuál es la indicación clásica para iniciar cateterismo intermitente limpio?', 'multiple_choice', ARRAY['Residuo posmiccional persistentemente elevado, aproximadamente mayor de 100 ml.', 'Cualquier urgencia miccional.', 'Incontinencia de esfuerzo.', 'Nicturia aislada.']::text[], 0, ARRAY['1sfw1us', 'kkc50b', 'vn5w5t', 'h9h6ip']::text[], '1sfw1us', 'La vejiga hipoactiva produce vaciamiento incompleto, retención e incontinencia por rebosamiento. Un residuo posmiccional persistentemente mayor de 100 ml es el umbral clásico para considerar cateterismo intermitente limpio. La urgencia corresponde con mayor frecuencia a vejiga hiperactiva; la nicturia o la incontinencia de esfuerzo aisladas no demuestran retención.

La evaluación incluye orina completa, urocultivo, ecografía con residuo posmiccional y urodinamia cuando está indicada. El umbral no es absoluto: también se consideran capacidad vesical, síntomas, infecciones recurrentes, presiones urodinámicas y función renal. Una medición aislada no basta para indicar cateterismo permanente.', 1, 21)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('cd09d288-3733-4e24-bf8c-47b23930a7c4', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de las siguientes medidas forma parte del manejo integral de la espasticidad?', 'multiple_choice', ARRAY['Únicamente tratamiento farmacológico.', 'Sólo fisioterapia.', 'Abordaje multidisciplinario con rehabilitación y tratamiento farmacológico cuando esté indicado.', 'Reposo prolongado.']::text[], 2, ARRAY['pv9sf7', '14v2a2c', '19ksu93', '15w79uo']::text[], '19ksu93', 'La espasticidad se trata según su distribución, gravedad, dolor e impacto funcional. El plan combina identificación de desencadenantes, ejercicio, estiramientos, postura, fisioterapia, terapia ocupacional, ortesis y medicación cuando aporta un beneficio concreto.

La espasticidad focal puede tratarse con toxina botulínica y rehabilitación; la generalizada puede requerir baclofeno, tizanidina o gabapentina. El reposo prolongado favorece debilidad y contracturas. Tampoco debe eliminarse el tono de manera indiscriminada: algunos pacientes lo utilizan para mantenerse de pie o realizar transferencias, y una relajación excesiva puede empeorar la función.', 1, 22)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('8a6b2e88-efbc-48f6-8cc9-3b9f7a9625f8', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', '¿Cuál de los siguientes fármacos se encuentra entre las opciones iniciales para el tratamiento del dolor neuropático persistente en esclerosis múltiple?', 'multiple_choice', ARRAY['Ibuprofeno.', 'Duloxetina.', 'Prednisona.', 'Tramadol como tratamiento inicial.']::text[], 1, ARRAY['tiewgc', '1li21w0', '1e58m9y', '2ewbqu']::text[], '1li21w0', 'Duloxetina es una opción para disestesias urentes y dolor neuropático persistente. Otras alternativas son venlafaxina, amitriptilina, gabapentina y pregabalina, elegidas según comorbilidades, tolerancia y tipo de dolor.

Ibuprofeno es más apropiado para dolor musculoesquelético que para dolor neuropático. Prednisona no es un analgésico crónico y se reserva para recaídas inflamatorias que requieren tratamiento. Tramadol y otros opioides no son opciones iniciales por su beneficio limitado y por los riesgos de sedación, tolerancia y dependencia. El dolor paroxístico, como Lhermitte o neuralgia del trigémino, suele responder mejor a fármacos como carbamazepina.', 1, 23)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

insert into academy_quiz_questions (id, quiz_id, question_text, question_type, options, correct_option_index, option_ids, correct_option_id, explanation, points, display_order)
values ('60d1edf8-7887-467b-a4e7-9b16a7d1170c', 'f1180a0d-921d-4d47-8c3d-3c56836124b2', 'Respecto al Symbol Digit Modalities Test (SDMT) en pacientes con esclerosis múltiple, ¿cuál de las siguientes afirmaciones es correcta?', 'multiple_choice', ARRAY['Evalúa principalmente memoria episódica verbal.', 'Es una prueba de screening de la velocidad de procesamiento y una de las herramientas más sensibles para detectar deterioro cognitivo en EM.', 'Requiere aproximadamente 45 minutos para su administración.', 'Ha sido reemplazado por el PASAT como herramienta de screening.']::text[], 1, ARRAY['wuxv3g', '1s3icn2', 'yrfnap', '1vwkcu7']::text[], '1s3icn2', 'El SDMT evalúa principalmente velocidad de procesamiento, atención y eficiencia visomotora. La tarea cronometrada dura 90 segundos y puede completarse, con instrucciones, en pocos minutos. Es una de las pruebas más sensibles para detectar y seguir deterioro cognitivo en esclerosis múltiple.

El PASAT fue desplazado en la práctica por ser más complejo, estresante y dependiente de una presentación auditiva estandarizada. Un SDMT alterado es una señal para ampliar la evaluación neuropsicológica, no un diagnóstico aislado. El resultado puede verse afectado por déficit visual o motor, fatiga, depresión, recaídas y efecto de aprendizaje.

Referencia: Kalb R et al. Recommendations for cognitive screening and management in multiple sclerosis care. Mult Scler. 2018;24:1665-1680.', 1, 24)
on conflict (id) do update set
  option_ids = excluded.option_ids,
  correct_option_id = excluded.correct_option_id;

-- 4. Repair the title mangled on import (shows up in the ranking view).
update academy_quizzes set title = 'Neurocognitivo y Psiquiatría' where id = '1eb7f501-e3c6-417d-9c38-b3dfa0c1698f';

-- 5. Drop the exact duplicate of "Examen de Semiologia 2024" (created 5s after its twin),
--    but only if nothing was ever recorded against it.
delete from academy_quiz_questions
where quiz_id = 'de9aa85a-e3b2-4058-9ff1-aa16916835aa'
  and not exists (select 1 from academy_quiz_attempts a where a.quiz_id = 'de9aa85a-e3b2-4058-9ff1-aa16916835aa');
delete from academy_quizzes
where id = 'de9aa85a-e3b2-4058-9ff1-aa16916835aa'
  and not exists (select 1 from academy_quiz_attempts a where a.quiz_id = 'de9aa85a-e3b2-4058-9ff1-aa16916835aa');

-- 6. Report: what the database looks like afterwards.
do $$
declare
  pending int;
  dup int;
begin
  select count(*) into pending from academy_quiz_questions where correct_option_id is null;
  select count(*) into dup from academy_quizzes where id = 'de9aa85a-e3b2-4058-9ff1-aa16916835aa';
  raise notice 'preguntas sin id estable: %', pending;
  raise notice 'duplicado de Semiologia todavia presente: %', dup;
end $$;

commit;
