-- Import 3 medical quizzes
DO $$
DECLARE
  quiz1_id UUID;
  quiz2_id UUID;
  quiz3_id UUID;
BEGIN
  -- Quiz 1: Neurorehabilitación 2025
  INSERT INTO academy_quizzes (title, description, time_limit_minutes, shuffle_questions, show_correct_answers, status, created_by)
  VALUES ('Neurorehabilitación 2025', 'Examen del módulo de Neurorehabilitación - Certificación SNA 2025', 30, false, true, 'published', 'system-import')
  RETURNING id INTO quiz1_id;

  INSERT INTO academy_quiz_questions (quiz_id, question_text, question_type, options, correct_option_index, explanation, points, display_order) VALUES
  (quiz1_id, 'En un paciente que presenta disfagia, la misma puede repercutir en:', 'multiple_choice', ARRAY['Su evolución neurológica y estado nutricional','Su evolución neurológica, estado nutricional y su aparato respiratorio','Estado nutricional','El aparato respiratorio','Su evolución neurológica'], 1, 'La disfagia puede afectar múltiples aspectos: evolución neurológica (por riesgo de complicaciones), estado nutricional (por dificultad en la alimentación) y aparato respiratorio (por riesgo de broncoaspiración).', 1, 0),
  (quiz1_id, 'Al realizar un abordaje con comunicación aumentativa alternativa, se está trabajando:', 'multiple_choice', ARRAY['El aspecto pragmático','La expresión oral','La funcionalidad comunicativa','La comprensión oral'], 2, 'La comunicación aumentativa alternativa se enfoca en mejorar la funcionalidad comunicativa del paciente mediante sistemas alternativos o complementarios al lenguaje oral.', 1, 1),
  (quiz1_id, 'El paradigma de rehabilitación actual defiende:', 'multiple_choice', ARRAY['El derecho a un trato igualitario, orientado a la inclusión social activa','La familia como pilar de rehabilitación','La marginación','La intervención profesional como solución'], 0, 'El paradigma actual de rehabilitación se centra en los derechos del paciente, promoviendo la igualdad y la inclusión social activa como objetivos fundamentales.', 1, 2),
  (quiz1_id, '¿Cuál de los siguientes factores cualifica mejor el pronóstico inicial en el departamento de emergencias?', 'multiple_choice', ARRAY['Duración de la amnesia post traumática','Tomografía computada o resonancia de ingreso','Tiempo de duración de la pérdida de conciencia','Glasgow Coma Scale','Mecanismo de lesión'], 3, 'La Escala de Glasgow (GCS) es el mejor predictor pronóstico inicial en emergencias, ya que evalúa de manera estandarizada el nivel de consciencia del paciente.', 1, 3),
  (quiz1_id, 'Según la OMS, el objetivo general de la neurorrehabilitación es:', 'multiple_choice', ARRAY['Restablecer las funciones motoras, sensitivas, sensoriales, cognitivas, emocionales, y los dominios sociales','Recuperar la marcha funcional','Restablecer aquellas funciones más comprometidas','Compensar los déficits con distintos elementos de apoyo (por ej elementos de ayuda marcha)'], 0, 'La OMS define la neurorrehabilitación de manera integral, buscando el restablecimiento de todas las funciones: motoras, sensitivas, sensoriales, cognitivas, emocionales y sociales.', 1, 4),
  (quiz1_id, '¿En qué momento de la neurorehabilitación es conveniente iniciar la rehabilitación cognitiva?', 'multiple_choice', ARRAY['Al alta, para que se realice en forma ambulatoria','Cuando el paciente lo demanda','Cuando el paciente se descomplejiza clínicamente','Desde el ingreso al centro de neurorehabilitación'], 2, 'La rehabilitación cognitiva debe iniciarse cuando el paciente se estabiliza clínicamente y su condición general permite participar activamente en las terapias.', 1, 5),
  (quiz1_id, '¿Por debajo de qué puntaje Z el rendimiento cognitivo es patológico?', 'multiple_choice', ARRAY['-1.5','0','-1','-2'], 0, 'Un puntaje Z por debajo de -1.5 desviaciones estándar se considera patológico en la evaluación del rendimiento cognitivo.', 1, 6),
  (quiz1_id, 'El equipamiento postural de los pacientes:', 'multiple_choice', ARRAY['Se confecciona el mismo equipamiento para todos los pacientes neurológicos','Es dinámico y personalizado','No requiere de ningún entrenamiento por parte de la TO','Si se indica al inicio del tratamiento, debe mantenerse el mismo hasta el momento del alta'], 1, 'El equipamiento postural debe ser individualizado según las necesidades de cada paciente y modificarse según su evolución, siendo dinámico y personalizado.', 1, 7),
  (quiz1_id, 'Los objetivos desde Terapia Ocupacional:', 'multiple_choice', ARRAY['Se plantean al momento del ingreso y se mantienen los mismos hasta el momento del alta','Solo deben tener en cuenta el diagnóstico del individuo','Son centrados en el paciente y se focalizan en las actividades y participación social del individuo','Están centrados en las funciones y estructuras corporales del individuo'], 2, 'Los objetivos de Terapia Ocupacional se centran en el paciente como persona, enfocándose en sus actividades cotidianas y su participación social, más allá de las limitaciones físicas.', 1, 8),
  (quiz1_id, 'La Neurorehabilitación se lleva a cabo a través de un grupo:', 'multiple_choice', ARRAY['Multidisciplinario','Transdisciplinario','Interdisciplinario','Sólo médicos neurólogos especialistas en neurorrehabilitación'], 2, 'La neurorehabilitación requiere un equipo interdisciplinario donde diferentes profesionales trabajan de manera coordinada e integrada.', 1, 9),
  (quiz1_id, 'La neurorehabilitación kinésica restaurativa tiene como medio:', 'multiple_choice', ARRAY['El mantenimiento del perfil de funcionalidad','La reversión de las deficiencias','La modulación de las deficiencias','El destete de las asistencias indicadas'], 2, 'La kinesiología restaurativa busca modular las deficiencias neurológicas mediante técnicas específicas de neurorehabilitación.', 1, 10),
  (quiz1_id, 'El abordaje de la espasticidad en un paciente neurológico:', 'multiple_choice', ARRAY['Es un objetivo básico de tratamiento kinésico','Su presencia es indicador de tratamiento kinésico restaurativo','Su presencia es indicador de tratamiento kinésico de mantenimiento','Su abordaje se relaciona con el impacto sobre una limitación de la actividad'], 3, 'El tratamiento de la espasticidad debe enfocarse en cómo esta afecta las actividades funcionales del paciente, no solo en su presencia.', 1, 11),
  (quiz1_id, '¿Cuáles de los siguientes son considerados factores de mal pronóstico en el daño axonal difuso?', 'multiple_choice', ARRAY['Edad mayor a 40 años','Duración del coma mayor a 20 días','A y B son correctas','Todas son correctas','Amnesia post traumática mayor a 2 semanas'], 2, 'Tanto la edad mayor a 40 años como la duración del coma mayor a 20 días son factores de mal pronóstico en el daño axonal difuso.', 1, 12),
  (quiz1_id, '¿Cuál de las siguientes NO es una característica del estado vegetativo?', 'multiple_choice', ARRAY['Conservación de ciclos sueño vigilia','Funciones autonómicas preservadas','Apertura ocular espontánea','Evidencia de respuesta voluntaria reproducible a estímulos','Ausencia de comprensión o expresión al lenguaje'], 3, 'El estado vegetativo se caracteriza por la ausencia de respuestas voluntarias reproducibles. Si hay evidencia de estas respuestas, el paciente no está en estado vegetativo.', 1, 13),
  (quiz1_id, '¿Cuál de las siguientes escalas evalúa la percepción personal del paciente?', 'multiple_choice', ARRAY['Escala analógica visual','FIM','Barthel Index','EDSS'], 0, 'La escala analógica visual es una herramienta subjetiva que evalúa la percepción personal del paciente, comúnmente usada para valorar dolor o bienestar.', 1, 14),
  (quiz1_id, 'En caso de vejiga con globos vesicales en lesión medular, ¿qué aconseja?', 'multiple_choice', ARRAY['Cateterismo intermitente','Tamsulosina','Sonda vesical permanente','Anticolinérgicos'], 0, 'El cateterismo intermitente es el método de elección para el manejo de la vejiga neurogénica con retención urinaria, reduciendo complicaciones infecciosas.', 1, 15),
  (quiz1_id, 'Las ortesis son utilizadas por los pacientes durante el proceso de rehabilitación. Indique cuál de las siguientes afirmaciones es incorrecta:', 'multiple_choice', ARRAY['Una ortesis es una extensión artificial que remplaza o provee una parte del cuerpo que falta por diversas causas','Una ortesis es un dispositivo de aplicación externa que se utiliza para modificar los aspectos funcionales o estructurales del sistema neuromuscular y esquelético','Las férulas antebraquio-palmares se utilizan para controlar la mano en garra','Las ortesis de pie-tobillo se utilizan para controlar el pie equino'], 0, 'La definición incorrecta es la primera: las prótesis reemplazan partes del cuerpo que faltan, mientras que las ortesis son dispositivos externos de soporte sin reemplazar partes del cuerpo.', 1, 16),
  (quiz1_id, 'Las ayudas para la marcha (APM) son utilizadas por el paciente neurológico durante la deambulación. ¿Cuál de las siguientes afirmaciones es correcta?', 'multiple_choice', ARRAY['El andador se utiliza en pacientes sin trastornos del equilibrio','El bastón trípode brinda mayor estabilidad en pacientes con trastornos del equilibrio','El bastón trípode no brinda mayor estabilidad en pacientes con trastornos del equilibrio','El bastón de un punto se utiliza en pacientes con trastornos del equilibrio'], 1, 'El bastón trípode, con su base de tres puntos de apoyo, proporciona mayor estabilidad que un bastón simple, siendo útil en pacientes con alteraciones del equilibrio.', 1, 17),
  (quiz1_id, 'La goniometría clínica es utilizada ampliamente en pacientes con secuelas ortopédicas y neurológicas. Marque la opción correcta:', 'multiple_choice', ARRAY['La goniometría se ocupa de medir y registrar la inflamación de cada una de las articulaciones del cuerpo humano','La goniometría se ocupa de medir y registrar el dolor de cada una de las articulaciones del cuerpo humano','La goniometría se ocupa de medir y registrar el arco de movimiento de cada una de las articulaciones del cuerpo humano','La goniometría se ocupa de medir y registrar la fuerza muscular de cada una de las articulaciones del cuerpo humano'], 2, 'La goniometría es la técnica de medición de los ángulos de movimiento articular, evaluando la amplitud del rango de movimiento de las articulaciones.', 1, 18),
  (quiz1_id, 'La evaluación inicial del paciente con Vejiga Neurogénica incluye:', 'multiple_choice', ARRAY['Clearence de creatinina, Ecografía renovesical, Examen físico, Urodinamia','Ecografía renovesical','Clearence de creatinina','Examen físico'], 0, 'La evaluación completa de la vejiga neurogénica requiere múltiples estudios: función renal (clearence), imágenes (ecografía), evaluación clínica y estudio funcional (urodinamia).', 1, 19),
  (quiz1_id, 'La posibilidad de definir que un sujeto tenga riesgo de caída se obtiene a través de:', 'multiple_choice', ARRAY['A través de la comparación de la medida de resultado con un punto de corte aplicable a la población en estudio','A través de la ponderación de la actividad y la observación clínica','La ponderación de la actividad limitada y la comparación de la medida de resultado con los valores normativos','Por medio de la observación clínica y la anamnesis correspondiente'], 0, 'El riesgo de caída se determina mediante escalas validadas que comparan los resultados del paciente con puntos de corte establecidos para la población específica.', 1, 20),
  (quiz1_id, 'Juan es una persona que sufrió un accidente cerebro vascular el cual le dejó como secuela una hemiplejia. Tiene disminución en la fuerza y espasticidad en su miembro inferior derecho, no puede realizar marcha, por lo que se moviliza en silla de ruedas. Actualmente ha tenido que dejar de trabajar ya que en su trabajo no hay rampas para que pueda acceder. SEGÚN LA CIF, EL ACCIDENTE CEREBRO VASCULAR ES:', 'multiple_choice', ARRAY['La secuela','La condición de salud de Juan','La discapacidad que le quedó','Una limitación en sus actividades'], 1, 'Según la Clasificación Internacional del Funcionamiento (CIF), el ACV es la condición de salud que genera las deficiencias, limitaciones y restricciones en la participación.', 1, 21),
  (quiz1_id, 'EL CÓDIGO CIF ESTÁ FORMADO POR:', 'multiple_choice', ARRAY['Una letra que representa el componente, números que representan las categorías seguido de un calificador','4 números que representan las categorías más una letra que es el calificador','Una letra que representa el componente y un calificador','Un código de una letra y 3 números'], 2, 'El código CIF se estructura con una letra inicial que identifica el componente (b=funciones corporales, s=estructuras, d=actividades, e=factores ambientales) seguida de un calificador numérico.', 1, 22),
  (quiz1_id, 'Paciente de 54 años de edad con secuela de ACV isquémico que presenta trastornos en el lenguaje expresivo y comprensivo, con déficit atencional y disfagia orofaríngea. Presenta los siguientes signos clínicos asociados: hemiparesia derecha, hemihipoestesia derecha y hemianopsia homónima derecha. Este cuadro sería compatible con:', 'multiple_choice', ARRAY['Afasia trascortical motora','Afasia mixta','Afasia global','Afasia de Wernicke','Afasia trascortical sensorial'], 2, 'La afasia global se caracteriza por compromiso severo tanto de la expresión como de la comprensión del lenguaje, asociada a hemiparesia y otros déficits neurológicos extensos.', 1, 23),
  (quiz1_id, 'Las actividades de la vida diaria se pueden categorizar en:', 'multiple_choice', ARRAY['Actividades de autocuidado, instrumentales, ocio y tiempo libre','Actividades de la vida diaria básicas, instrumentales y avanzadas','Actividades de ocio y tiempo libre, cuidado de otros y actividades básicas','Actividades de autocuidado, cuidado de la salud y actividades avanzadas'], 1, 'Las AVD se clasifican en tres categorías: básicas (autocuidado), instrumentales (manejo del hogar y entorno) y avanzadas (trabajo, ocio, roles sociales).', 1, 24);

  -- Quiz 2: Epilepsia 2025
  INSERT INTO academy_quizzes (title, description, time_limit_minutes, shuffle_questions, show_correct_answers, status, created_by)
  VALUES ('Epilepsia 2025', 'Examen final del módulo de Epilepsia - Certificación SNA 2025', 35, false, true, 'published', 'system-import')
  RETURNING id INTO quiz2_id;

  INSERT INTO academy_quiz_questions (quiz_id, question_text, question_type, options, correct_option_index, explanation, points, display_order) VALUES
  (quiz2_id, 'Considerando la definición clínico-operativa de epilepsia, ¿en cuál de los siguientes casos NO se consideraría la presencia de epilepsia?', 'multiple_choice', ARRAY['Paciente que ha presentado 2 crisis epilépticas no provocadas, con un intervalo entre crisis de 20 años','Mujer de 56 años con antecedentes de encefalitis herpética hace 1 año, que ha sufrido su primera crisis no provocada','Niño de 8 años que presentó una crisis epiléptica mientras jugaba con videojuegos. La misma situación se repitió 48Hs después (EEG: respuesta foto-paroxística anormal)','Hombre diabético insulino-dependiente, que presentó una primera crisis en contexto de hipoglucemia, y una segunda crisis a la semana, sin causa ni detonante aparente (EEG: normal, RMN de encéfalo: lesiones vasculares puntiformes)'], 3, 'La primera crisis fue provocada (hipoglucemia). Para considerar epilepsia, se requieren crisis no provocadas. Una única crisis no provocada posterior no cumple los criterios de epilepsia.', 1, 0),
  (quiz2_id, '¿Cuál es el riesgo de recaída después de dos crisis no provocadas a los 2 años de seguimiento?', 'multiple_choice', ARRAY['20%','40%','60%','10%'], 2, 'El riesgo de recaída tras dos crisis no provocadas es aproximadamente del 60% a los 2 años, justificando el inicio de tratamiento antiepiléptico.', 1, 1),
  (quiz2_id, 'El protocolo de RM en epilepsia focal comprende:', 'multiple_choice', ARRAY['T1 axial','FLAIR Sagital','T2 Axial','IR Axial'], 2, 'El protocolo de RM en epilepsia focal incluye secuencias T2 axiales, entre otras, para detectar lesiones estructurales epileptogénicas.', 1, 2),
  (quiz2_id, 'Concurre a su consultorio una paciente de 64 años que refiere luces de colores intermitentes en el hemicampo izquierdo de 1 minuto de duración estereotipadas semanales. Usted sospecha epilepsia, ¿cuál es el área de inicio ictal más probable?', 'multiple_choice', ARRAY['Lóbulo frontal','Lóbulo temporal','Lóbulo parietal','Lóbulo occipital'], 3, 'Las alucinaciones visuales simples (luces de colores) sugieren un origen en el lóbulo occipital, donde se procesa la información visual primaria.', 1, 3),
  (quiz2_id, '¿Cuál de los siguientes medicamentos antiepilépticos tiene como efecto adverso grave un riesgo elevado de acidosis metabólica debido a la inhibición de la anhidrasa carbónica y riesgo de provocar litiasis renal en algunos pacientes?', 'multiple_choice', ARRAY['Valproato','Topiramato','Fenobarbital','Oxcarbazepina'], 1, 'El topiramato inhibe la anhidrasa carbónica, lo que puede causar acidosis metabólica y aumentar el riesgo de litiasis renal por alteración del pH urinario.', 1, 4),
  (quiz2_id, 'Ante el antecedente de una primera crisis no provocada, el riesgo de recaída a los 2 años de seguimiento es:', 'multiple_choice', ARRAY['Mayor al 60%','Entre 21-45%','Menor al 20%','Depende del tipo de crisis epiléptica sufrida'], 1, 'El riesgo de recurrencia tras una primera crisis no provocada es del 21-45% a los 2 años, lo que generalmente no justifica inicio de tratamiento antiepiléptico.', 1, 5),
  (quiz2_id, 'Indique la opción INCORRECTA respecto de la crisis focal con alteración del estado de conciencia:', 'multiple_choice', ARRAY['No es pérdida de conciencia sino una alteración más cualitativa de la misma','Generalmente se acompaña de automatismos','Forma parte de las epilepsias focales con síntomas cognitivos','Frecuentemente son difíciles de diferenciar de las epilepsias generalizadas de tipo ausencias'], 2, 'Las crisis focales con alteración de conciencia no se clasifican como epilepsias con síntomas cognitivos, sino que representan un tipo específico de crisis focal.', 1, 6),
  (quiz2_id, '¿Cuál de las siguientes opciones describe mejor los síntomas en una crisis con focalidad parietal?', 'multiple_choice', ARRAY['Parestesias, vértigo','Fenómeno de déja vu','Síntomas gustativos','Síntomas auditivos'], 0, 'El lóbulo parietal procesa información sensorial, por lo que las crisis parietales típicamente producen parestesias y pueden asociarse a vértigo.', 1, 7),
  (quiz2_id, '¿Cuál es el objetivo de la evaluación prequirúrgica en epilepsia focal?', 'multiple_choice', ARRAY['Establecer localización de área epileptogénica','Determinar el riesgo de déficit postoperatorio','Pronosticar resultados posquirúrgicos','Todas son correctas'], 3, 'La evaluación prequirúrgica tiene múltiples objetivos: localizar el área epileptogénica, evaluar riesgos y establecer pronóstico quirúrgico.', 1, 8),
  (quiz2_id, 'El electroencefalograma estándar tiene un tiempo de duración de:', 'multiple_choice', ARRAY['Mayor a 60 minutos','20-30 minutos','30-40 minutos','Menor a 20 minutos'], 1, 'El EEG estándar tiene una duración típica de 20-30 minutos, suficiente para registrar actividad basal y realizar maniobras de activación.', 1, 9),
  (quiz2_id, 'En el Status Epiléptico (SE), ¿a los cuántos minutos se produce el daño neuronal irreversible?', 'multiple_choice', ARRAY['30 minutos','5 minutos','20 minutos','60 minutos'], 0, 'El daño neuronal irreversible comienza aproximadamente a los 30 minutos de status epiléptico, por lo que es crucial el tratamiento rápido.', 1, 10),
  (quiz2_id, 'Respecto a la epilepsia generalizada genética, ¿cuál de las siguientes opciones NO corresponde a esta categoría?', 'multiple_choice', ARRAY['Epilepsia mioclónica juvenil','Epilepsia de ausencias infantil','Epilepsia con crisis tónico-clónicas generalizadas','Epilepsia focal de la infancia'], 3, 'La epilepsia focal de la infancia no es una epilepsia generalizada genética, sino una epilepsia focal con características específicas.', 1, 11),
  (quiz2_id, '¿Cuál de los siguientes fármacos podría exacerbar las ausencias típicas?', 'multiple_choice', ARRAY['Etosuccimida','Lamotrigina','Carbamazepina','Valproato'], 2, 'La carbamazepina puede empeorar las crisis de ausencias y no debe usarse en epilepsias generalizadas con este tipo de crisis.', 1, 12),
  (quiz2_id, 'Respecto a la Muerte Súbita Inesperada en Epilepsia (SUDEP), ¿cuál es la afirmación correcta?', 'multiple_choice', ARRAY['Es más frecuente en epilepsias generalizadas que en focales','Solo ocurre durante las crisis epilépticas','Su principal factor de riesgo es el mal control de crisis tónico-clónicas generalizadas','No existe relación con las crisis nocturnas'], 2, 'El principal factor de riesgo de SUDEP es el mal control de las crisis tónico-clónicas generalizadas, especialmente las nocturnas.', 1, 13),
  (quiz2_id, 'El pronóstico de las epilepsias se basa en:', 'multiple_choice', ARRAY['Etiología, respuesta al tratamiento','Tipo de crisis epilépticas','Síndrome epiléptico','Todas son correctas'], 3, 'El pronóstico epiléptico depende de múltiples factores: etiología, tipo de crisis, respuesta terapéutica y síndrome epiléptico identificado.', 1, 14),
  (quiz2_id, '¿Cuál es el fármaco de elección en una paciente femenina con epilepsia de ausencias juvenil que planifica un embarazo?', 'multiple_choice', ARRAY['Levetiracetam','Lamotrigina','Valproato','Carbamazepina'], 1, 'La lamotrigina es el fármaco de elección en mujeres con epilepsia generalizada que planifican embarazo, por su mejor perfil de seguridad fetal.', 1, 15),
  (quiz2_id, '¿Qué síndrome epiléptico presenta como característica electroencefalográfica polipunta onda generalizada a 4-6 Hz y tiene un buen pronóstico?', 'multiple_choice', ARRAY['Síndrome de West','Epilepsia mioclónica juvenil','Síndrome de Lennox-Gastaut','Epilepsia de ausencias infantil'], 1, 'La epilepsia mioclónica juvenil presenta polipunta-onda a 4-6 Hz y tiene buen pronóstico con tratamiento adecuado, aunque requiere medicación de por vida.', 1, 16),
  (quiz2_id, 'Respecto al tratamiento del Status Epiléptico Convulsivo, ¿cuál es la secuencia correcta de tratamiento?', 'multiple_choice', ARRAY['Benzodiacepinas - Fenitoína/Levetiracetam - Anestésicos','Fenitoína - Benzodiacepinas - Valproato','Anestésicos - Benzodiacepinas - Levetiracetam','Valproato - Fenitoína - Benzodiacepinas'], 0, 'La secuencia correcta es: benzodiacepinas como primera línea, seguidas de fenitoína o levetiracetam, y anestésicos si hay refractariedad.', 1, 17),
  (quiz2_id, '¿Cuál de los siguientes NO es un criterio diagnóstico de epilepsia según la ILAE 2014?', 'multiple_choice', ARRAY['Al menos 2 crisis no provocadas separadas por más de 24 horas','Una crisis no provocada con alto riesgo de recurrencia (mayor al 60%)','Diagnóstico de un síndrome epiléptico','Crisis provocadas recurrentes en contexto de enfermedad aguda'], 3, 'Las crisis provocadas recurrentes no definen epilepsia, ya que esta requiere crisis no provocadas o alto riesgo de recurrencia.', 1, 18),
  (quiz2_id, '¿Cuál es la principal indicación de monitoreo video-EEG prolongado?', 'multiple_choice', ARRAY['Caracterización de eventos paroxísticos de naturaleza indeterminada','Control de rutina de pacientes con epilepsia','Ajuste de medicación antiepiléptica','Seguimiento de pacientes post-quirúrgicos'], 0, 'El video-EEG prolongado está principalmente indicado para caracterizar eventos paroxísticos cuando hay dudas diagnósticas o para evaluación prequirúrgica.', 1, 19),
  (quiz2_id, 'En relación con el Síndrome de West, ¿cuál de las siguientes afirmaciones es correcta?', 'multiple_choice', ARRAY['La edad de inicio es típicamente después de los 2 años','El EEG característico muestra hipsarritmia','Las crisis características son las ausencias atípicas','El pronóstico a largo plazo es generalmente bueno'], 1, 'El Síndrome de West se caracteriza por la triada: espasmos infantiles, hipsarritmia en EEG y regresión del desarrollo, con inicio típico en el primer año.', 1, 20),
  (quiz2_id, '¿Cuál de los siguientes antiepilépticos tiene menor interacción con anticonceptivos orales?', 'multiple_choice', ARRAY['Carbamazepina','Fenitoína','Levetiracetam','Fenobarbital'], 2, 'El levetiracetam no tiene interacciones significativas con anticonceptivos orales, a diferencia de los inductores enzimáticos como carbamazepina o fenitoína.', 1, 21),
  (quiz2_id, 'El electroencefalograma de sueño tiene como objetivo:', 'multiple_choice', ARRAY['Evaluar trastornos del sueño','Aumentar la sensibilidad para detectar actividad epileptiforme','Confirmar el diagnóstico de epilepsia','Todas son correctas'], 1, 'El EEG de sueño aumenta la sensibilidad para detectar actividad epileptiforme, especialmente en epilepsias focales y generalizadas.', 1, 22),
  (quiz2_id, 'En el contexto de epilepsia y embarazo, ¿cuál de las siguientes afirmaciones es correcta?', 'multiple_choice', ARRAY['El valproato es el fármaco de elección','Se debe suspender la medicación antiepiléptica durante el embarazo','La suplementación con ácido fólico debe iniciarse antes de la concepción','Las crisis epilépticas no representan riesgo para el feto'], 2, 'El ácido fólico debe suplementarse idealmente desde antes de la concepción para reducir el riesgo de defectos del tubo neural, especialmente con valproato.', 1, 23),
  (quiz2_id, 'Respecto a las crisis febriles, ¿cuál es la afirmación correcta?', 'multiple_choice', ARRAY['Ocurren típicamente entre los 6 meses y 5 años de edad','Siempre requieren tratamiento antiepiléptico de mantenimiento','El riesgo de desarrollar epilepsia es superior al 50%','Son un tipo de epilepsia generalizada genética'], 0, 'Las crisis febriles típicas ocurren entre 6 meses y 5 años, son generalmente benignas y no requieren tratamiento antiepiléptico de mantenimiento.', 1, 24);

  -- Quiz 3: Enfermedades Cerebrovasculares 2024
  INSERT INTO academy_quizzes (title, description, time_limit_minutes, shuffle_questions, show_correct_answers, status, created_by)
  VALUES ('Enfermedades Cerebrovasculares 2024', 'Examen del módulo de Enfermedades Cerebrovasculares - Certificación SNA 2024', 35, false, true, 'published', 'system-import')
  RETURNING id INTO quiz3_id;

  INSERT INTO academy_quiz_questions (quiz_id, question_text, question_type, options, correct_option_index, explanation, points, display_order) VALUES
  (quiz3_id, '¿Cuáles son los factores de riesgo modificables del ACV isquémico?', 'multiple_choice', ARRAY['HTA, tabaquismo, cardiopatías, dislipidemia, obesidad, DBT, sedentarismo, alcoholismo, ACO, FA, estenosis carotídea','Edad, sexo y etnicidad','Genéticos','Todas son correctas'], 0, 'Los factores de riesgo modificables incluyen hipertensión, tabaquismo, cardiopatías, dislipidemia, obesidad, diabetes, sedentarismo, alcoholismo, anticonceptivos orales, FA y estenosis carotídea.', 1, 0),
  (quiz3_id, '¿Cuál es la ventana temporal recomendada para el tratamiento con alteplase EV?', 'multiple_choice', ARRAY['3 horas','4.5 horas','6 horas','Ninguna de las anteriores'], 1, 'La ventana para alteplase EV es de 4.5 horas desde el inicio de los síntomas, con mayor beneficio cuanto más temprano se administre.', 1, 1),
  (quiz3_id, 'Ante un paciente con ACV isquémico que recibió fibrinólisis y presenta deterioro del sensorio y midriasis, ¿cuál es la conducta inicial?', 'multiple_choice', ARRAY['Suspender fibrinólisis y realizar TC de encéfalo','Administrar plasma fresco congelado','Continuar monitoreo clínico','Administrar vitamina K'], 0, 'Ante sospecha de hemorragia post-fibrinolisis, se debe suspender el tratamiento inmediatamente y realizar TC de encéfalo urgente para confirmar.', 1, 2),
  (quiz3_id, '¿Cuáles son las principales arterias que irrigan el polígono de Willis?', 'multiple_choice', ARRAY['Carótidas internas y sistema vertebrobasilar','Solo carótidas internas','Solo sistema vertebrobasilar','Carótidas externas'], 0, 'El polígono de Willis recibe irrigación de las carótidas internas (circulación anterior) y del sistema vertebrobasilar (circulación posterior).', 1, 3),
  (quiz3_id, 'Indique la escala utilizada para evaluación de severidad del ACV:', 'multiple_choice', ARRAY['NIHSS','Escala de Glasgow','Escala de Rankin modificada','ASPECTS'], 0, 'La escala NIHSS (National Institutes of Health Stroke Scale) es el estándar para evaluar la severidad del ACV isquémico agudo.', 1, 4),
  (quiz3_id, '¿Cuál es el tiempo puerta-aguja recomendado para la fibrinólisis en ACV isquémico?', 'multiple_choice', ARRAY['Menor a 60 minutos','Menor a 45 minutos','Menor a 30 minutos','Menor a 90 minutos'], 0, 'El tiempo puerta-aguja recomendado es menor a 60 minutos para maximizar el beneficio de la fibrinólisis.', 1, 5),
  (quiz3_id, 'En el contexto de ACV isquémico agudo, ¿cuál es la presión arterial objetivo antes de la fibrinólisis?', 'multiple_choice', ARRAY['Mayor a 185/110 mmHg','Menor a 185/110 mmHg','Menor a 140/90 mmHg','Mayor a 220/120 mmHg'], 1, 'La PA debe ser menor a 185/110 mmHg antes de iniciar fibrinólisis y mantenerse menor a 180/105 durante las primeras 24 horas post-tratamiento.', 1, 6),
  (quiz3_id, '¿Cuál es la principal contraindicación absoluta para fibrinólisis EV?', 'multiple_choice', ARRAY['ACV isquémico previo hace 4 meses','Hemorragia intracraneal previa','Cirugía menor hace 2 semanas','Punción lumbar hace 10 días'], 1, 'La hemorragia intracraneal previa es una contraindicación absoluta para fibrinólisis debido al alto riesgo de sangrado recurrente.', 1, 7),
  (quiz3_id, 'El síndrome de Wallenberg se produce por oclusión de:', 'multiple_choice', ARRAY['Arteria cerebral media','Arteria cerebelosa posteroinferior','Arteria cerebral anterior','Arteria basilar'], 1, 'El síndrome de Wallenberg o síndrome bulbar lateral se produce por oclusión de la arteria cerebelosa posteroinferior (PICA) o arteria vertebral.', 1, 8),
  (quiz3_id, '¿Cuál es el mecanismo más frecuente de ACV isquémico?', 'multiple_choice', ARRAY['Cardioembólico','Aterotrombótico de grandes vasos','Enfermedad de pequeño vaso (lacunar)','Disección arterial'], 1, 'El mecanismo aterotrombótico de grandes vasos es el más frecuente, seguido por cardioembolia y enfermedad de pequeño vaso.', 1, 9),
  (quiz3_id, '¿Qué estudio de imagen se recomienda como primera línea en sospecha de ACV agudo?', 'multiple_choice', ARRAY['Resonancia magnética de encéfalo','Tomografía computada de encéfalo sin contraste','Angiografía cerebral','Doppler carotídeo'], 1, 'La TC de encéfalo sin contraste es el estudio de primera línea porque descarta hemorragia rápidamente y está ampliamente disponible.', 1, 10),
  (quiz3_id, 'En el ACV isquémico de circulación posterior, ¿cuál de los siguientes síntomas NO es característico?', 'multiple_choice', ARRAY['Vértigo','Diplopía','Ataxia','Afasia de Broca'], 3, 'La afasia de Broca es característica de lesiones de circulación anterior (arteria cerebral media izquierda), no de circulación posterior.', 1, 11),
  (quiz3_id, '¿Cuál es el score ASPECTS mínimo recomendado para considerar trombectomía mecánica?', 'multiple_choice', ARRAY['Mayor o igual a 6','Mayor o igual a 4','Mayor o igual a 8','No existe límite inferior'], 0, 'Un ASPECTS de 6 o mayor se considera favorable para trombectomía mecánica, indicando menor extensión del infarto establecido.', 1, 12),
  (quiz3_id, '¿Cuál es la ventana temporal actual para trombectomía mecánica según los ensayos DAWN y DEFUSE 3?', 'multiple_choice', ARRAY['6 horas','12 horas','24 horas','48 horas'], 2, 'Los ensayos DAWN y DEFUSE 3 demostraron beneficio de trombectomía hasta 24 horas en pacientes seleccionados por imagen de perfusión.', 1, 13),
  (quiz3_id, 'La anticoagulación está indicada en prevención secundaria de ACV isquémico en caso de:', 'multiple_choice', ARRAY['Fibrilación auricular','Estenosis carotídea sintomática','Enfermedad de pequeño vaso','Todas las anteriores'], 0, 'La anticoagulación está indicada en FA para prevención secundaria de ACV cardioembólico. Las otras causas se manejan con antiagregación.', 1, 14),
  (quiz3_id, '¿Cuál es el antídoto específico para revertir el efecto del dabigatrán?', 'multiple_choice', ARRAY['Vitamina K','Idarucizumab','Concentrado de complejo protrombínico','Plasma fresco congelado'], 1, 'El idarucizumab es el antídoto específico del dabigatrán, un anticuerpo monoclonal que revierte su efecto anticoagulante.', 1, 15),
  (quiz3_id, 'En el contexto de hemorragia intracerebral, ¿cuál es la localización más frecuente?', 'multiple_choice', ARRAY['Lobar','Putaminal','Talámica','Cerebelosa'], 1, 'La localización putaminal (ganglios basales) es la más frecuente en HIC hipertensiva, seguida por la talámica.', 1, 16),
  (quiz3_id, '¿Cuál es la meta de presión arterial en las primeras horas de una hemorragia intracerebral según las guías actuales?', 'multiple_choice', ARRAY['Menor a 180/110 mmHg','Menor a 140 mmHg de sistólica','Menor a 160/100 mmHg','Mayor a 140 mmHg de sistólica'], 1, 'Las guías actuales recomiendan mantener la PAS menor a 140 mmHg en las primeras horas de HIC para reducir la expansión del hematoma.', 1, 17),
  (quiz3_id, '¿Cuál de los siguientes factores predice expansión del hematoma intracerebral?', 'multiple_choice', ARRAY['Signo del punto en angioTC','Volumen inicial pequeño','Presión arterial controlada','Tiempo de evolución mayor a 6 horas'], 0, 'El signo del punto (spot sign) en angioTC indica extravasación activa de contraste y predice expansión del hematoma.', 1, 18),
  (quiz3_id, 'En la hemorragia subaracnoidea aneurismática, ¿cuál es el período de mayor riesgo de vasoespasmo?', 'multiple_choice', ARRAY['Primeras 24 horas','Días 3-14','Después del día 21','No existe período definido'], 1, 'El vasoespasmo cerebral ocurre típicamente entre los días 3-14 post-HSA, con pico entre los días 7-10.', 1, 19),
  (quiz3_id, '¿Cuál es el tratamiento de elección para prevenir vasoespasmo en HSA?', 'multiple_choice', ARRAY['Nimodipina','Clazosentán','Estatinas','Magnesio'], 0, 'La nimodipina es el único tratamiento con evidencia demostrada para mejorar los outcomes neurológicos en HSA por vasoespasmo.', 1, 20),
  (quiz3_id, '¿Qué escala se utiliza para clasificar la severidad clínica de la hemorragia subaracnoidea?', 'multiple_choice', ARRAY['Escala de Hunt y Hess','Escala de Glasgow','NIHSS','Escala de Fisher'], 0, 'La escala de Hunt y Hess clasifica la severidad clínica de la HSA, mientras que la escala de Fisher clasifica la cantidad de sangre en TC.', 1, 21),
  (quiz3_id, '¿Cuál es la causa más frecuente de hemorragia subaracnoidea no traumática?', 'multiple_choice', ARRAY['Malformación arteriovenosa','Ruptura de aneurisma cerebral','Angiopatía amiloide','Coagulopatía'], 1, 'La ruptura de aneurisma cerebral es la causa de aproximadamente 85% de las HSA no traumáticas.', 1, 22),
  (quiz3_id, '¿Cuál de los siguientes NO es un factor de riesgo para formación o ruptura de aneurismas cerebrales?', 'multiple_choice', ARRAY['Hipertensión arterial','Tabaquismo','Diabetes mellitus','Antecedentes familiares de aneurismas'], 2, 'La diabetes mellitus no es un factor de riesgo establecido para aneurismas cerebrales, a diferencia de HTA, tabaquismo y factores genéticos.', 1, 23),
  (quiz3_id, '¿En cuál de estos casos NO es necesario realizar una angiografía digital cerebral para descartar causa secundaria de HIC?', 'multiple_choice', ARRAY['HIC lobar en mayores de 70 años','HIV (hemorragia interventricular) sin hemorragia intraparenquimatosa','HIC profunda o posterior en menores de 45 años','Edema o efecto de masa desproporcionado al tiempo de evolución y calcificaciones anormales'], 0, 'HIC lobar en mayores de 70 años generalmente se debe a angiopatía amiloide o HTA, no requiriendo angiografía rutinaria. Los otros casos tienen mayor sospecha de causa vascular estructural.', 1, 24);

  RAISE NOTICE 'Successfully imported 3 quizzes with 75 questions total';
END $$;
